// AUTO-GENERATED by tools/artkit/gen-character-roster.mjs — re-run after promoting characters.
// §7 playable character roster. Each id keys an INSTALLED sprite
// manifest (public/sprites/<id>/). Purely visual for M0 (stats live on §11 attributes); per-character
// class/variant passives are a follow-on. Legacy ids remain available for compatibility and dev inspection;
// ordinary selection and cycling use the whole-art subset.

export const PLAYABLE_CHARACTERS = [
  "drifter",
  "cc-asha-the-ash-walker",
  "cc-bastion-vance",
  "cc-brother-cassian-the-ashen-crusader",
  "cc-brother-tendo-of-the-still-bell",
  "cc-bryda-houndcall",
  "cc-buzzard-jeptha-hale",
  "cc-cinderpyre",
  "cc-cogwarden",
  "cc-cordell-coldsnap-vane",
  "cc-corvane-the-crimson-draught",
  "cc-crowmantle-sel",
  "cc-dame-veyra-of-the-thornwatch",
  "cc-deepfall-korr",
  "cc-doctor-phineas-quill-esq",
  "cc-dunkel-the-coinblade",
  "cc-elias-parson-thorne",
  "cc-gravewake",
  "cc-grix-boltcaster",
  "cc-halcyon-7",
  "cc-hollowmaw",
  "cc-iridia-of-the-nine-veils",
  "cc-kuro-oni-the-demon-mask",
  "cc-magdalene-the-ledger-crowe",
  "cc-mawkin-sourgrin-the-hex-witch",
  "cc-mei-ling-of-the-jade-ribbon",
  "cc-mirelurk-caine",
  "cc-neon-mirage",
  "cc-pyra-cinderhowl-the-flame-caster",
  "cc-quickfinger-odette-lacroix",
  "cc-raijin-k-the-storm-fist",
  "cc-s-jiro-the-wayward-blade",
  "cc-sable-cipher",
  "cc-sir-galloway-the-unbending",
  "cc-sir-mordrane-the-hollow-oath",
  "cc-the-bandida-la-sombra",
  "cc-the-hollow-mask",
  "cc-thornroot",
  "cc-tinker-magnus-brasswick",
  "cc-yuki-the-hollow-smile",
  "proto-armored-bean-heavy",
  "proto-blob-bruiser",
  "proto-capsule-tactical-unit",
  "proto-geometric-robot-pod",
  "proto-helmeted-enforcer",
  "proto-hooded-rogue",
  "proto-masked-oval-fighter",
  "proto-mutant-lump",
  "proto-paper-cutout-fighter",
  "proto-samurai",
  "proto-sheriff",
  "proto-soft-mascot-fighter",
  "proto-witch",
] as const;

export type PlayableCharacter = (typeof PLAYABLE_CHARACTERS)[number];

/** Installed whole-art characters available to ordinary player selection. */
export const WHOLE_ART_CHARACTERS = [
  "proto-armored-bean-heavy",
  "proto-blob-bruiser",
  "proto-capsule-tactical-unit",
  "proto-geometric-robot-pod",
  "proto-helmeted-enforcer",
  "proto-hooded-rogue",
  "proto-masked-oval-fighter",
  "proto-mutant-lump",
  "proto-paper-cutout-fighter",
  "proto-samurai",
  "proto-sheriff",
  "proto-soft-mascot-fighter",
  "proto-witch",
] as const satisfies readonly PlayableCharacter[];

export type WholeArtCharacter = (typeof WHOLE_ART_CHARACTERS)[number];

/** Â§classmerge sum-10 starting identity and signature quirk; generated beside the roster so every
 * promoted playable must deliberately receive a kit before generation can succeed. */
export const CHARACTER_KITS = {
  "drifter": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "cc-asha-the-ash-walker": { spread: { str: 2, dex: 2, int: 2, con: 3, luk: 1 }, quirk: "mend-the-broken" },
  "cc-bastion-vance": { spread: { str: 3, dex: 1, int: 1, con: 4, luk: 1 }, quirk: "planted" },
  "cc-brother-cassian-the-ashen-crusader": { spread: { str: 3, dex: 1, int: 1, con: 4, luk: 1 }, quirk: "habit-and-prayer" },
  "cc-brother-tendo-of-the-still-bell": { spread: { str: 3, dex: 2, int: 1, con: 3, luk: 1 }, quirk: "one-perfect-strike" },
  "cc-bryda-houndcall": { spread: { str: 3, dex: 3, int: 1, con: 2, luk: 1 }, quirk: "the-pack-finds-you" },
  "cc-buzzard-jeptha-hale": { spread: { str: 3, dex: 2, int: 1, con: 2, luk: 2 }, quirk: "overstuffed-bandoliers" },
  "cc-cinderpyre": { spread: { str: 2, dex: 1, int: 4, con: 2, luk: 1 }, quirk: "molten-core" },
  "cc-cogwarden": { spread: { str: 3, dex: 1, int: 1, con: 4, luk: 1 }, quirk: "does-not-stop" },
  "cc-cordell-coldsnap-vane": { spread: { str: 1, dex: 3, int: 1, con: 2, luk: 3 }, quirk: "coldsnap" },
  "cc-corvane-the-crimson-draught": { spread: { str: 1, dex: 1, int: 4, con: 3, luk: 1 }, quirk: "the-crimson-draught" },
  "cc-crowmantle-sel": { spread: { str: 1, dex: 3, int: 1, con: 1, luk: 4 }, quirk: "a-better-owner" },
  "cc-dame-veyra-of-the-thornwatch": { spread: { str: 2, dex: 4, int: 1, con: 2, luk: 1 }, quirk: "insufferably-graceful" },
  "cc-deepfall-korr": { spread: { str: 3, dex: 1, int: 2, con: 3, luk: 1 }, quirk: "mag-boots" },
  "cc-doctor-phineas-quill-esq": { spread: { str: 1, dex: 2, int: 3, con: 1, luk: 3 }, quirk: "snake-oil" },
  "cc-dunkel-the-coinblade": { spread: { str: 2, dex: 2, int: 1, con: 2, luk: 3 }, quirk: "hazard-rates" },
  "cc-elias-parson-thorne": { spread: { str: 2, dex: 2, int: 2, con: 1, luk: 3 }, quirk: "graveside-manner" },
  "cc-gravewake": { spread: { str: 2, dex: 1, int: 2, con: 3, luk: 2 }, quirk: "already-dead" },
  "cc-grix-boltcaster": { spread: { str: 3, dex: 1, int: 1, con: 3, luk: 2 }, quirk: "braced" },
  "cc-halcyon-7": { spread: { str: 1, dex: 3, int: 2, con: 2, luk: 2 }, quirk: "half-projection" },
  "cc-hollowmaw": { spread: { str: 2, dex: 1, int: 4, con: 2, luk: 1 }, quirk: "whispered-rites" },
  "cc-iridia-of-the-nine-veils": { spread: { str: 1, dex: 2, int: 4, con: 1, luk: 2 }, quirk: "sees-every-future" },
  "cc-kuro-oni-the-demon-mask": { spread: { str: 3, dex: 2, int: 1, con: 3, luk: 1 }, quirk: "temple-wall" },
  "cc-magdalene-the-ledger-crowe": { spread: { str: 2, dex: 3, int: 1, con: 2, luk: 2 }, quirk: "posted" },
  "cc-mawkin-sourgrin-the-hex-witch": { spread: { str: 1, dex: 1, int: 4, con: 2, luk: 2 }, quirk: "bottled-spite" },
  "cc-mei-ling-of-the-jade-ribbon": { spread: { str: 1, dex: 4, int: 2, con: 1, luk: 2 }, quirk: "ribbon-step" },
  "cc-mirelurk-caine": { spread: { str: 3, dex: 2, int: 1, con: 3, luk: 1 }, quirk: "bog-patience" },
  "cc-neon-mirage": { spread: { str: 1, dex: 4, int: 1, con: 2, luk: 2 }, quirk: "package-deal" },
  "cc-pyra-cinderhowl-the-flame-caster": { spread: { str: 2, dex: 2, int: 4, con: 1, luk: 1 }, quirk: "let-it-out" },
  "cc-quickfinger-odette-lacroix": { spread: { str: 1, dex: 2, int: 1, con: 2, luk: 4 }, quirk: "the-house" },
  "cc-raijin-k-the-storm-fist": { spread: { str: 4, dex: 2, int: 1, con: 2, luk: 1 }, quirk: "thunder-behind" },
  "cc-s-jiro-the-wayward-blade": { spread: { str: 3, dex: 4, int: 1, con: 1, luk: 1 }, quirk: "iai" },
  "cc-sable-cipher": { spread: { str: 1, dex: 4, int: 2, con: 1, luk: 2 }, quirk: "ice-breaker" },
  "cc-sir-galloway-the-unbending": { spread: { str: 2, dex: 1, int: 1, con: 4, luk: 2 }, quirk: "the-unbending" },
  "cc-sir-mordrane-the-hollow-oath": { spread: { str: 3, dex: 1, int: 2, con: 3, luk: 1 }, quirk: "hollow-oath" },
  "cc-the-bandida-la-sombra": { spread: { str: 2, dex: 3, int: 1, con: 1, luk: 3 }, quirk: "a-shape-in-the-dust" },
  "cc-the-hollow-mask": { spread: { str: 1, dex: 4, int: 1, con: 1, luk: 3 }, quirk: "porcelain" },
  "cc-thornroot": { spread: { str: 2, dex: 1, int: 2, con: 4, luk: 1 }, quirk: "regrow" },
  "cc-tinker-magnus-brasswick": { spread: { str: 1, dex: 2, int: 4, con: 2, luk: 1 }, quirk: "pressurized" },
  "cc-yuki-the-hollow-smile": { spread: { str: 2, dex: 4, int: 1, con: 1, luk: 2 }, quirk: "fox-dance" },
  "proto-armored-bean-heavy": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-blob-bruiser": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-capsule-tactical-unit": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-geometric-robot-pod": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-helmeted-enforcer": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-hooded-rogue": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-masked-oval-fighter": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-mutant-lump": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-paper-cutout-fighter": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-samurai": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-sheriff": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-soft-mascot-fighter": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
  "proto-witch": { spread: { str: 2, dex: 2, int: 2, con: 2, luk: 2 }, quirk: "unwritten" },
} as const satisfies Record<PlayableCharacter, {
  readonly spread: Readonly<Record<"str" | "dex" | "int" | "con" | "luk", number>>;
  readonly quirk: string;
}>;

export const DEFAULT_CHARACTER = "proto-sheriff" as const satisfies WholeArtCharacter;

/** Next character in the full legacy-compatible roster, wrapping. */
export function nextCharacter(current: string): string {
  const i = PLAYABLE_CHARACTERS.indexOf(current as (typeof PLAYABLE_CHARACTERS)[number]);
  return PLAYABLE_CHARACTERS[(i + 1) % PLAYABLE_CHARACTERS.length] ?? DEFAULT_CHARACTER;
}

/** Untrusted-id guard for the ordinary whole-art selection contract. */
export function isWholeArtCharacter(id: unknown): id is WholeArtCharacter {
  return (
    typeof id === "string" && (WHOLE_ART_CHARACTERS as readonly string[]).includes(id)
  );
}

/** Next ordinary whole-art character, wrapping; legacy/unknown ids reset to the shared default. */
export function nextWholeArtCharacter(current: string): WholeArtCharacter {
  const i = WHOLE_ART_CHARACTERS.indexOf(current as WholeArtCharacter);
  if (i < 0) return DEFAULT_CHARACTER;
  return WHOLE_ART_CHARACTERS[(i + 1) % WHOLE_ART_CHARACTERS.length] ?? DEFAULT_CHARACTER;
}

/** Pretty display name for the HUD (falls back to a title-cased id). */
export function characterName(id: string): string {
  return (
    CHARACTER_NAMES[id] ??
    id
      .replace(/^cc-/, "")
      .replace(/-/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase())
  );
}

const CHARACTER_NAMES: Record<string, string> = {
  "drifter": "The Drifter",
  "cc-asha-the-ash-walker": "Asha the Ash-Walker",
  "cc-bastion-vance": "Bastion Vance",
  "cc-brother-cassian-the-ashen-crusader": "Brother Cassian",
  "cc-brother-tendo-of-the-still-bell": "Brother Tendo of the Still Bell",
  "cc-bryda-houndcall": "Bryda Houndcall",
  "cc-buzzard-jeptha-hale": "Buzzard",
  "cc-cinderpyre": "Cinderpyre",
  "cc-cogwarden": "Cogwarden",
  "cc-cordell-coldsnap-vane": "Cordell \"Coldsnap\" Vane",
  "cc-corvane-the-crimson-draught": "Corvane the Crimson Draught",
  "cc-crowmantle-sel": "Crowmantle Sel",
  "cc-dame-veyra-of-the-thornwatch": "Dame Veyra of the Thornwatch",
  "cc-deepfall-korr": "Deepfall Korr",
  "cc-doctor-phineas-quill-esq": "Doctor Phineas Quill, Esq.",
  "cc-dunkel-the-coinblade": "Dunkel the Coinblade",
  "cc-elias-parson-thorne": "Elias \"Parson\" Thorne",
  "cc-gravewake": "Gravewake",
  "cc-grix-boltcaster": "Grix Boltcaster",
  "cc-halcyon-7": "Halcyon-7",
  "cc-hollowmaw": "Hollowmaw",
  "cc-iridia-of-the-nine-veils": "Iridia of the Nine Veils",
  "cc-kuro-oni-the-demon-mask": "Kuro-Oni, the Demon Mask",
  "cc-magdalene-the-ledger-crowe": "Magdalene \"The Ledger\" Crowe",
  "cc-mawkin-sourgrin-the-hex-witch": "Mawkin Sourgrin the Hex-Witch",
  "cc-mei-ling-of-the-jade-ribbon": "Mei-Ling of the Jade Ribbon",
  "cc-mirelurk-caine": "Mirelurk Caine",
  "cc-neon-mirage": "Neon Mirage",
  "cc-pyra-cinderhowl-the-flame-caster": "Pyra Cinderhowl",
  "cc-quickfinger-odette-lacroix": "\"Quickfinger\" Odette Lacroix",
  "cc-raijin-k-the-storm-fist": "Raijin Kō, the Storm Fist",
  "cc-s-jiro-the-wayward-blade": "Sōjiro the Wayward Blade",
  "cc-sable-cipher": "Sable Cipher",
  "cc-sir-galloway-the-unbending": "Sir Galloway the Unbending",
  "cc-sir-mordrane-the-hollow-oath": "Sir Mordrane, the Hollow Oath",
  "cc-the-bandida-la-sombra": "The Bandida \"La Sombra\"",
  "cc-the-hollow-mask": "The Hollow Mask",
  "cc-thornroot": "Thornroot",
  "cc-tinker-magnus-brasswick": "Tinker-Magnus Brasswick",
  "cc-yuki-the-hollow-smile": "Yuki",
  "proto-armored-bean-heavy": "Prototype Armored Bean Heavy",
  "proto-blob-bruiser": "Prototype Blob Bruiser",
  "proto-capsule-tactical-unit": "Prototype Capsule Tactical Unit",
  "proto-geometric-robot-pod": "Prototype Geometric Robot Pod",
  "proto-helmeted-enforcer": "Prototype Helmeted Enforcer",
  "proto-hooded-rogue": "Prototype Hooded Rogue",
  "proto-masked-oval-fighter": "Prototype Masked Oval Fighter",
  "proto-mutant-lump": "Prototype Mutant Lump",
  "proto-paper-cutout-fighter": "Prototype Paper Cutout Fighter",
  "proto-samurai": "Prototype Samurai",
  "proto-sheriff": "Prototype Sheriff",
  "proto-soft-mascot-fighter": "Prototype Soft Mascot Fighter",
  "proto-witch": "Prototype Witch",
};

/** §7 per-character render-scale bump for small-footprint skins (so the thin/compact ones don't read as
 *  tiny next to the chunky ones). 1.0 = no change; the client multiplies the rig by this. */
export function characterScale(id: string): number {
  return CHARACTER_SCALE[id] ?? 1;
}
const CHARACTER_SCALE: Record<string, number> = {
  "cc-asha-the-ash-walker": 1.114,
  "cc-brother-cassian-the-ashen-crusader": 1.128,
  "cc-brother-tendo-of-the-still-bell": 1.116,
  "cc-bryda-houndcall": 1.25,
  "cc-corvane-the-crimson-draught": 1.06,
  "cc-crowmantle-sel": 1.185,
  "cc-dame-veyra-of-the-thornwatch": 1.142,
  "cc-doctor-phineas-quill-esq": 1.117,
  "cc-elias-parson-thorne": 1.25,
  "cc-hollowmaw": 1.116,
  "cc-mawkin-sourgrin-the-hex-witch": 1.097,
  "cc-pyra-cinderhowl-the-flame-caster": 1.25,
  "cc-sable-cipher": 1.25,
  "cc-the-hollow-mask": 1.12,
  "cc-tinker-magnus-brasswick": 1.22,
  "cc-yuki-the-hollow-smile": 1.25,
};
