// AUTO-GENERATED by tools/artkit/gen-character-roster.mjs — re-run after promoting characters.
// §7 playable character roster (cosmetic skins; the C key cycles them). Each id keys an INSTALLED sprite
// manifest (public/sprites/<id>/). Purely visual for M0 (stats live on §11 attributes); per-character
// class/variant passives are a follow-on. The Drifter is the default + the §28.3 "pill grunt" anchor.

export const PLAYABLE_CHARACTERS = [
  "drifter",
  "cc-asha-the-ash-walker",
  "cc-bastion-vance",
  "cc-brother-cassian-the-ashen-crusader",
  "cc-brother-tendo-of-the-still-bell",
  "cc-bryda-houndcall",
  "cc-buzzard-jeptha-hale",
  "cc-cinderpyre",
  "cc-cogwarden",
  "cc-cordell-coldsnap-vane",
  "cc-corvane-the-crimson-draught",
  "cc-crowmantle-sel",
  "cc-dame-veyra-of-the-thornwatch",
  "cc-deepfall-korr",
  "cc-doctor-phineas-quill-esq",
  "cc-dunkel-the-coinblade",
  "cc-elias-parson-thorne",
  "cc-gravewake",
  "cc-grix-boltcaster",
  "cc-halcyon-7",
  "cc-hollowmaw",
  "cc-iridia-of-the-nine-veils",
  "cc-kuro-oni-the-demon-mask",
  "cc-magdalene-the-ledger-crowe",
  "cc-mawkin-sourgrin-the-hex-witch",
  "cc-mei-ling-of-the-jade-ribbon",
  "cc-mirelurk-caine",
  "cc-neon-mirage",
  "cc-pyra-cinderhowl-the-flame-caster",
  "cc-quickfinger-odette-lacroix",
  "cc-raijin-k-the-storm-fist",
  "cc-s-jiro-the-wayward-blade",
  "cc-sable-cipher",
  "cc-sir-galloway-the-unbending",
  "cc-sir-mordrane-the-hollow-oath",
  "cc-the-bandida-la-sombra",
  "cc-the-hollow-mask",
  "cc-thornroot",
  "cc-tinker-magnus-brasswick",
  "cc-yuki-the-hollow-smile",
] as const;

export const DEFAULT_CHARACTER = "drifter";

/** Next character in the roster, wrapping. PURE (server cycles authoritatively; client mirrors). */
export function nextCharacter(current: string): string {
  const i = PLAYABLE_CHARACTERS.indexOf(current as (typeof PLAYABLE_CHARACTERS)[number]);
  return PLAYABLE_CHARACTERS[(i + 1) % PLAYABLE_CHARACTERS.length] ?? DEFAULT_CHARACTER;
}

/** Pretty display name for the HUD (falls back to a title-cased id). */
export function characterName(id: string): string {
  return (
    CHARACTER_NAMES[id] ??
    id
      .replace(/^cc-/, "")
      .replace(/-/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase())
  );
}

const CHARACTER_NAMES: Record<string, string> = {
  drifter: "The Drifter",
  "cc-asha-the-ash-walker": "Asha the Ash-Walker",
  "cc-bastion-vance": "Bastion Vance",
  "cc-brother-cassian-the-ashen-crusader": "Brother Cassian",
  "cc-brother-tendo-of-the-still-bell": "Brother Tendo of the Still Bell",
  "cc-bryda-houndcall": "Bryda Houndcall",
  "cc-buzzard-jeptha-hale": "Buzzard",
  "cc-cinderpyre": "Cinderpyre",
  "cc-cogwarden": "Cogwarden",
  "cc-cordell-coldsnap-vane": 'Cordell "Coldsnap" Vane',
  "cc-corvane-the-crimson-draught": "Corvane the Crimson Draught",
  "cc-crowmantle-sel": "Crowmantle Sel",
  "cc-dame-veyra-of-the-thornwatch": "Dame Veyra of the Thornwatch",
  "cc-deepfall-korr": "Deepfall Korr",
  "cc-doctor-phineas-quill-esq": "Doctor Phineas Quill, Esq.",
  "cc-dunkel-the-coinblade": "Dunkel the Coinblade",
  "cc-elias-parson-thorne": 'Elias "Parson" Thorne',
  "cc-gravewake": "Gravewake",
  "cc-grix-boltcaster": "Grix Boltcaster",
  "cc-halcyon-7": "Halcyon-7",
  "cc-hollowmaw": "Hollowmaw",
  "cc-iridia-of-the-nine-veils": "Iridia of the Nine Veils",
  "cc-kuro-oni-the-demon-mask": "Kuro-Oni, the Demon Mask",
  "cc-magdalene-the-ledger-crowe": 'Magdalene "The Ledger" Crowe',
  "cc-mawkin-sourgrin-the-hex-witch": "Mawkin Sourgrin the Hex-Witch",
  "cc-mei-ling-of-the-jade-ribbon": "Mei-Ling of the Jade Ribbon",
  "cc-mirelurk-caine": "Mirelurk Caine",
  "cc-neon-mirage": "Neon Mirage",
  "cc-pyra-cinderhowl-the-flame-caster": "Pyra Cinderhowl",
  "cc-quickfinger-odette-lacroix": '"Quickfinger" Odette Lacroix',
  "cc-raijin-k-the-storm-fist": "Raijin Kō, the Storm Fist",
  "cc-s-jiro-the-wayward-blade": "Sōjiro the Wayward Blade",
  "cc-sable-cipher": "Sable Cipher",
  "cc-sir-galloway-the-unbending": "Sir Galloway the Unbending",
  "cc-sir-mordrane-the-hollow-oath": "Sir Mordrane, the Hollow Oath",
  "cc-the-bandida-la-sombra": 'The Bandida "La Sombra"',
  "cc-the-hollow-mask": "The Hollow Mask",
  "cc-thornroot": "Thornroot",
  "cc-tinker-magnus-brasswick": "Tinker-Magnus Brasswick",
  "cc-yuki-the-hollow-smile": "Yuki",
};
