// AUTO-GENERATED by tools/artkit/gen-dimensions.mjs — DO NOT EDIT.
// The §17 themed dimensions + their all-tier enemy rosters + the 3 cross-dimensional shifters, codegen'd
// from data/dimensions-design.json + data/dimension-shifters.json. shared/dimensions.ts merges
// EXTRA_DIMENSIONS into DIMENSIONS; shared/enemies.ts merges DIMENSION_ENEMY_KINDS into ENEMY_KINDS.
// Re-run the script after editing either data file. (Wild West stays hand-authored in those modules.)

import type { DimensionDef } from "./dimensions.js";
import type { EnemyKind } from "./enemies.js";

export const EXTRA_DIMENSIONS: Record<string, DimensionDef> = {
  "frostfell": {
    "id": "frostfell",
    "name": "Frostfell",
    "tagline": "The cathedral froze mid-prayer, and the prayer answered.",
    "roster": [
      "frostbitten-revenant",
      "shriek-wraith",
      "hoarfrost-bloom",
      "rimebound-archer",
      "frozen-knight"
    ],
    "boss": "the-hollow-king",
    "hazard": {
      "name": "Black-ice slicks",
      "description": "Glassy frozen meltwater sheets the nave in dark mirror-slicks. Step on one and you keep sliding — momentum carries you past where you stopped steering, drifting into contact range or off the lip of a frozen pit. A pale freezing fog clings low over each slick so the edges read before you commit (§17)."
    },
    "palette": {
      "groundBed": 0x1c2330,
      "gridColor1": 0x1c2330,
      "gridColor2": 0x23303f,
      "boundaryRail": 0x3c6e6a,
      "pitVoid": 0x070a12,
      "pitRustBand": 0x2e6e9e,
      "pitAmberLip": 0x9fd8e8,
      "spawnRingSafe": 0x33e6ff,
      "dustDrift": 0xcfe0e8
    },
    "assets": {
      "tile": "tile-ground",
      "poiSet": "frostfell",
      "decalSet": "frostfell"
    }
  },
  "verdant-ruins": {
    "id": "verdant-ruins",
    "name": "Verdant Ruins",
    "tagline": "The jungle ate the temple, and the temple woke up.",
    "roster": [
      "vine-lasher",
      "venom-spore",
      "fungal-bloomer",
      "blowdart-sentinel",
      "thornblade-warden"
    ],
    "boss": "moss-stone-golem",
    "hazard": {
      "name": "Toxin-spore pools",
      "description": "Sump-puddles of luminous green spore-rot well up between the broken flagstones — stand in one for a stacking poison chip and slowed footing until you step clear (§17)."
    },
    "palette": {
      "groundBed": 0x1c2a1e,
      "gridColor1": 0x1c2a1e,
      "gridColor2": 0x243a26,
      "boundaryRail": 0x6e7042,
      "pitVoid": 0x0a120c,
      "pitRustBand": 0x3c6e3a,
      "pitAmberLip": 0xc4b24a,
      "spawnRingSafe": 0x33e6ff,
      "dustDrift": 0x9cff3b
    },
    "assets": {
      "tile": "tile-ground",
      "poiSet": "verdant-ruins",
      "decalSet": "verdant-ruins"
    }
  },
  "ashlands": {
    "id": "ashlands",
    "name": "Ashlands",
    "tagline": "Cracked magma, falling ash, and the brute below.",
    "roster": [
      "cinder-imp",
      "ember-mote",
      "slag-crawler",
      "ember-spitter",
      "magma-duelist"
    ],
    "boss": "molten-brute",
    "hazard": {
      "name": "Lava cracks & fire vents",
      "description": "Glowing fissures split the basalt floor and pressure-vents flare on a cycle — the §17 pit-rim language re-skinned as molten cracks (hot amber lip = the burn telegraph). Standing on a lit crack or a venting tile chips you and snap-repositions, same as a Wild-West mineshaft fall; the cool cyan spawn ring stays the one safe pad."
    },
    "palette": {
      "groundBed": 0x1a1210,
      "gridColor1": 0x1a1210,
      "gridColor2": 0x261713,
      "boundaryRail": 0x9e3b36,
      "pitVoid": 0x120608,
      "pitRustBand": 0xc0341f,
      "pitAmberLip": 0xff8a2b,
      "spawnRingSafe": 0x33e6ff,
      "dustDrift": 0x6e3a24
    },
    "assets": {
      "tile": "tile-ground",
      "poiSet": "ashlands",
      "decalSet": "ashlands"
    }
  },
  "neon-cyber": {
    "id": "neon-cyber",
    "name": "Neon-Cyber",
    "tagline": "Chrome streets, killbots, and the live grid.",
    "roster": [
      "synthrunner",
      "dronemite",
      "turret-node",
      "laser-spire",
      "riot-enforcer"
    ],
    "boss": "warden-mech",
    "hazard": {
      "name": "Live laser grid",
      "description": "An electrified circuit grid pulses across the plaza floor — lines of arc-violet current snap ON in telegraphed rows/columns, and standing on a hot trace chips you (a shock tick + brief stagger) until it cycles dark. Read the pattern, cross on the cooldown beat (§17)."
    },
    "palette": {
      "groundBed": 0x171a21,
      "gridColor1": 0x171a21,
      "gridColor2": 0x1e2a33,
      "boundaryRail": 0xff3bd4,
      "pitVoid": 0x08060e,
      "pitRustBand": 0xb14bff,
      "pitAmberLip": 0x33e6ff,
      "spawnRingSafe": 0x9cff3b,
      "dustDrift": 0x3c6e6a
    },
    "assets": {
      "tile": "tile-ground",
      "poiSet": "neon-cyber",
      "decalSet": "neon-cyber"
    }
  }
};

export const DIMENSION_ENEMY_KINDS: Record<string, EnemyKind> = {
  "frostbitten-revenant": {
    "sprite": "frostbitten-revenant",
    "archetype": "rusher",
    "speed": 172,
    "hp": 3,
    "radius": 18,
    "contactDamage": 4,
    "weight": 5,
    "moneyValue": 1
  },
  "shriek-wraith": {
    "sprite": "shriek-wraith",
    "archetype": "swarm",
    "speed": 228,
    "hp": 1,
    "radius": 12,
    "contactDamage": 2.5,
    "weight": 4,
    "moneyValue": 1
  },
  "hoarfrost-bloom": {
    "sprite": "hoarfrost-bloom",
    "archetype": "zoner",
    "speed": 60,
    "hp": 9,
    "radius": 26,
    "contactDamage": 6,
    "weight": 2,
    "moneyValue": 3
  },
  "rimebound-archer": {
    "sprite": "rimebound-archer",
    "archetype": "spitter",
    "speed": 122,
    "hp": 5,
    "radius": 20,
    "contactDamage": 3.5,
    "weight": 2,
    "moneyValue": 3,
    "ranged": {
      "range": 580,
      "preferredRange": 360,
      "cooldown": 2,
      "damage": 8,
      "projectileSpeed": 320
    }
  },
  "frozen-knight": {
    "sprite": "frozen-knight",
    "archetype": "duelist",
    "renderScale": 1.22,
    "speed": 150,
    "hp": 40,
    "radius": 23,
    "contactDamage": 0,
    "weight": 0.7,
    "moneyValue": 10,
    "melee": {
      "approach": 152,
      "range": 144,
      "halfArc": 0.92,
      "damage": 14,
      "hits": 3,
      "windup": 0.54,
      "swingGap": 0.34,
      "recover": 0.98,
      "step": 74
    },
    "wieldsWeapon": "x-sword-coffin",
    "dropWeapon": 0.35
  },
  "the-hollow-king": {
    "sprite": "the-hollow-king",
    "archetype": "boss",
    "renderScale": 2.7,
    "speed": 70,
    "hp": 440,
    "radius": 64,
    "contactDamage": 14,
    "weight": 0,
    "moneyValue": 40,
    "ranged": {
      "range": 780,
      "preferredRange": 380,
      "cooldown": 1.6,
      "damage": 13,
      "projectileSpeed": 320
    },
    "wieldsWeapon": "tombstone-greatsword",
    "dropWeapon": 0
  },
  "vine-lasher": {
    "sprite": "vine-lasher",
    "archetype": "rusher",
    "speed": 172,
    "hp": 3,
    "radius": 18,
    "contactDamage": 4,
    "weight": 5,
    "moneyValue": 1
  },
  "venom-spore": {
    "sprite": "venom-spore",
    "archetype": "swarm",
    "speed": 228,
    "hp": 1,
    "radius": 12,
    "contactDamage": 2.5,
    "weight": 4,
    "moneyValue": 1
  },
  "fungal-bloomer": {
    "sprite": "fungal-bloomer",
    "archetype": "zoner",
    "speed": 62,
    "hp": 9,
    "radius": 26,
    "contactDamage": 6,
    "weight": 2,
    "moneyValue": 3
  },
  "blowdart-sentinel": {
    "sprite": "blowdart-sentinel",
    "archetype": "spitter",
    "speed": 120,
    "hp": 5,
    "radius": 20,
    "contactDamage": 3.5,
    "weight": 2,
    "moneyValue": 3,
    "ranged": {
      "range": 560,
      "preferredRange": 350,
      "cooldown": 2.1,
      "damage": 8,
      "projectileSpeed": 300
    }
  },
  "thornblade-warden": {
    "sprite": "thornblade-warden",
    "archetype": "duelist",
    "renderScale": 1.2,
    "speed": 158,
    "hp": 38,
    "radius": 22,
    "contactDamage": 0,
    "weight": 0.7,
    "moneyValue": 9,
    "melee": {
      "approach": 150,
      "range": 140,
      "halfArc": 0.9,
      "damage": 13,
      "hits": 3,
      "windup": 0.52,
      "swingGap": 0.34,
      "recover": 0.95,
      "step": 72
    },
    "wieldsWeapon": "x-sword-coffin",
    "dropWeapon": 0.35
  },
  "moss-stone-golem": {
    "sprite": "moss-stone-golem",
    "archetype": "boss",
    "renderScale": 2.7,
    "speed": 70,
    "hp": 440,
    "radius": 66,
    "contactDamage": 14,
    "weight": 0,
    "moneyValue": 42,
    "ranged": {
      "range": 720,
      "preferredRange": 340,
      "cooldown": 1.7,
      "damage": 12,
      "projectileSpeed": 300,
      "spread": {
        "count": 3,
        "arc": 0.5
      }
    },
    "wieldsWeapon": "tombstone-greatsword",
    "dropWeapon": 0
  },
  "cinder-imp": {
    "sprite": "cinder-imp",
    "archetype": "rusher",
    "speed": 174,
    "hp": 3,
    "radius": 18,
    "contactDamage": 4,
    "weight": 5,
    "moneyValue": 1
  },
  "ember-mote": {
    "sprite": "ember-mote",
    "archetype": "swarm",
    "speed": 228,
    "hp": 1,
    "radius": 12,
    "contactDamage": 2.5,
    "weight": 4,
    "moneyValue": 1
  },
  "slag-crawler": {
    "sprite": "slag-crawler",
    "archetype": "zoner",
    "speed": 60,
    "hp": 9,
    "radius": 26,
    "contactDamage": 6,
    "weight": 2,
    "moneyValue": 3
  },
  "ember-spitter": {
    "sprite": "ember-spitter",
    "archetype": "spitter",
    "speed": 122,
    "hp": 5,
    "radius": 20,
    "contactDamage": 3.5,
    "weight": 2,
    "moneyValue": 3,
    "ranged": {
      "range": 560,
      "preferredRange": 340,
      "cooldown": 2,
      "damage": 8,
      "projectileSpeed": 300
    }
  },
  "magma-duelist": {
    "sprite": "magma-duelist",
    "archetype": "duelist",
    "renderScale": 1.2,
    "speed": 152,
    "hp": 40,
    "radius": 22,
    "contactDamage": 0,
    "weight": 0.7,
    "moneyValue": 10,
    "melee": {
      "approach": 150,
      "range": 140,
      "halfArc": 0.9,
      "damage": 14,
      "hits": 3,
      "windup": 0.52,
      "swingGap": 0.34,
      "recover": 0.95,
      "step": 72
    },
    "wieldsWeapon": "x-sword-bone",
    "dropWeapon": 0.35
  },
  "molten-brute": {
    "sprite": "molten-brute",
    "archetype": "boss",
    "renderScale": 2.7,
    "speed": 70,
    "hp": 440,
    "radius": 66,
    "contactDamage": 15,
    "weight": 0,
    "moneyValue": 42,
    "ranged": {
      "range": 780,
      "preferredRange": 360,
      "cooldown": 1.6,
      "damage": 13,
      "projectileSpeed": 320
    },
    "wieldsWeapon": "x-sword-coffin",
    "dropWeapon": 1
  },
  "synthrunner": {
    "sprite": "synthrunner",
    "archetype": "rusher",
    "speed": 172,
    "hp": 3,
    "radius": 18,
    "contactDamage": 4,
    "weight": 5,
    "moneyValue": 1
  },
  "dronemite": {
    "sprite": "dronemite",
    "archetype": "swarm",
    "speed": 228,
    "hp": 1,
    "radius": 12,
    "contactDamage": 2.5,
    "weight": 4,
    "moneyValue": 1
  },
  "turret-node": {
    "sprite": "turret-node",
    "archetype": "zoner",
    "speed": 60,
    "hp": 9,
    "radius": 26,
    "contactDamage": 6,
    "weight": 2,
    "moneyValue": 3
  },
  "laser-spire": {
    "sprite": "laser-spire",
    "archetype": "spitter",
    "speed": 122,
    "hp": 5,
    "radius": 20,
    "contactDamage": 3.5,
    "weight": 2,
    "moneyValue": 3,
    "ranged": {
      "range": 580,
      "preferredRange": 360,
      "cooldown": 2,
      "damage": 8,
      "projectileSpeed": 320
    }
  },
  "riot-enforcer": {
    "sprite": "riot-enforcer",
    "archetype": "duelist",
    "renderScale": 1.18,
    "speed": 156,
    "hp": 36,
    "radius": 22,
    "contactDamage": 0,
    "weight": 0.7,
    "moneyValue": 9,
    "melee": {
      "approach": 150,
      "range": 138,
      "halfArc": 0.9,
      "damage": 13,
      "hits": 3,
      "windup": 0.52,
      "swingGap": 0.34,
      "recover": 0.95,
      "step": 72
    },
    "wieldsWeapon": "x-gun-revolver-cannon",
    "dropWeapon": 0.35
  },
  "warden-mech": {
    "sprite": "warden-mech",
    "archetype": "boss",
    "renderScale": 2.7,
    "speed": 70,
    "hp": 420,
    "radius": 64,
    "contactDamage": 14,
    "weight": 0,
    "moneyValue": 40,
    "ranged": {
      "range": 760,
      "preferredRange": 360,
      "cooldown": 1.6,
      "damage": 13,
      "projectileSpeed": 320
    },
    "wieldsWeapon": "x-gun-gatling",
    "dropWeapon": 1
  },
  "shifter-cinder-marshal": {
    "sprite": "shifter-cinder-marshal",
    "archetype": "spitter",
    "renderScale": 1.2,
    "speed": 132,
    "hp": 64,
    "radius": 26,
    "contactDamage": 0,
    "weight": 0,
    "moneyValue": 25,
    "ranged": {
      "range": 640,
      "preferredRange": 380,
      "cooldown": 1.5,
      "damage": 14,
      "projectileSpeed": 340
    },
    "wieldsWeapon": "x-gun-revolver-cannon",
    "dropWeapon": 0.4,
    "shifter": {
      "tier": 1,
      "window": 22
    }
  },
  "shifter-voltaic-ronin": {
    "sprite": "shifter-voltaic-ronin",
    "archetype": "duelist",
    "renderScale": 1.22,
    "speed": 158,
    "hp": 88,
    "radius": 27,
    "contactDamage": 0,
    "weight": 0,
    "moneyValue": 35,
    "melee": {
      "approach": 162,
      "range": 144,
      "halfArc": 0.9,
      "damage": 12,
      "hits": 3,
      "windup": 0.5,
      "swingGap": 0.3,
      "recover": 0.85,
      "step": 82
    },
    "wieldsWeapon": "x-sword-neon-katana",
    "dropWeapon": 0.4,
    "shifter": {
      "tier": 2,
      "window": 20
    }
  },
  "shifter-grave-warden": {
    "sprite": "shifter-grave-warden",
    "archetype": "duelist",
    "renderScale": 1.35,
    "speed": 96,
    "hp": 108,
    "radius": 30,
    "contactDamage": 0,
    "weight": 0,
    "moneyValue": 50,
    "melee": {
      "approach": 150,
      "range": 152,
      "halfArc": 1.05,
      "damage": 20,
      "hits": 2,
      "windup": 0.72,
      "swingGap": 0.5,
      "recover": 1.25,
      "step": 64
    },
    "wieldsWeapon": "x-sword-coffin",
    "dropWeapon": 0.5,
    "shifter": {
      "tier": 3,
      "window": 24
    }
  }
};
