// AUTO-GENERATED by tools/artkit/gen-weapon-muzzles.mjs — do not edit by hand.
import type { WeaponArtMuzzleDefinition } from "./weapon-muzzle.js";

export const WEAPON_ART_MUZZLES = {
  "x-gun-coffin-shotgun": {
    "sprite": "x-gun-coffin-shotgun",
    "parts": [
      {
        "width": 256,
        "height": 103
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 30.9,
        "derived": {
          "x": 255,
          "y": 30.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x-gun-gatling": {
    "sprite": "x-gun-gatling",
    "parts": [
      {
        "width": 280,
        "height": 186
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 279,
        "y": 57.4,
        "derived": {
          "x": 279,
          "y": 57.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x-gun-hand-mortar": {
    "sprite": "x-gun-hand-mortar",
    "parts": [
      {
        "width": 256,
        "height": 130
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 37.4,
        "derived": {
          "x": 255,
          "y": 37.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x-gun-nailgun": {
    "sprite": "x-gun-nailgun",
    "parts": [
      {
        "width": 256,
        "height": 137
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 61,
        "derived": {
          "x": 255,
          "y": 61
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x-gun-revolver-cannon": {
    "sprite": "x-gun-revolver-cannon",
    "parts": [
      {
        "width": 256,
        "height": 136
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 23.9,
        "derived": {
          "x": 255,
          "y": 23.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x-gun-ricochet-pistol": {
    "sprite": "x-gun-ricochet-pistol",
    "parts": [
      {
        "width": 256,
        "height": 154
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 25.9,
        "derived": {
          "x": 255,
          "y": 25.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-ashfall-peacemaker": {
    "sprite": "x2-ashfall-peacemaker",
    "parts": [
      {
        "width": 256,
        "height": 129
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17.2,
        "derived": {
          "x": 255,
          "y": 17.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-auroral-filament-wand": {
    "sprite": "x2-auroral-filament-wand",
    "parts": [
      {
        "width": 256,
        "height": 33
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 16,
        "derived": {
          "x": 255,
          "y": 16
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-barrett-50-cal-sniper": {
    "sprite": "x2-barrett-50-cal-sniper",
    "parts": [
      {
        "width": 256,
        "height": 48
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 15.5,
        "derived": {
          "x": 255,
          "y": 15.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-boneash-scattergun-rifle": {
    "sprite": "x2-boneash-scattergun-rifle",
    "parts": [
      {
        "width": 256,
        "height": 73
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 11.8,
        "derived": {
          "x": 255,
          "y": 11.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-bonepicker-coachgun": {
    "sprite": "x2-bonepicker-coachgun",
    "parts": [
      {
        "width": 256,
        "height": 105
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 19.9,
        "derived": {
          "x": 255,
          "y": 19.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-boneyard-ricochet-mortar": {
    "sprite": "x2-boneyard-ricochet-mortar",
    "parts": [
      {
        "width": 256,
        "height": 195
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 81.5,
        "derived": {
          "x": 255,
          "y": 81.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-boomstick-saddlegun": {
    "sprite": "x2-boomstick-saddlegun",
    "parts": [
      {
        "width": 256,
        "height": 106
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.1,
        "derived": {
          "x": 255,
          "y": 13.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-brasswork-volley-rifle": {
    "sprite": "x2-brasswork-volley-rifle",
    "parts": [
      {
        "width": 256,
        "height": 68
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 10.6,
        "derived": {
          "x": 255,
          "y": 10.6
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-brimstone-bull": {
    "sprite": "x2-brimstone-bull",
    "parts": [
      {
        "width": 256,
        "height": 135
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 29.2,
        "derived": {
          "x": 255,
          "y": 29.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-brimstone-gallows-rifle": {
    "sprite": "x2-brimstone-gallows-rifle",
    "parts": [
      {
        "width": 256,
        "height": 85
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.3,
        "derived": {
          "x": 255,
          "y": 13.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-brimstone-rocket-tube": {
    "sprite": "x2-brimstone-rocket-tube",
    "parts": [
      {
        "width": 256,
        "height": 92
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 39.5,
        "derived": {
          "x": 255,
          "y": 39.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-brinequill-tidescepter": {
    "sprite": "x2-brinequill-tidescepter",
    "parts": [
      {
        "width": 256,
        "height": 67
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 33,
        "derived": {
          "x": 255,
          "y": 33
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-buckshot-avalanche": {
    "sprite": "x2-buckshot-avalanche",
    "parts": [
      {
        "width": 256,
        "height": 102
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 19.8,
        "derived": {
          "x": 255,
          "y": 19.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-buckshot-bramble-bow": {
    "sprite": "x2-buckshot-bramble-bow",
    "parts": [
      {
        "width": 256,
        "height": 202
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 246,
        "y": 102,
        "derived": {
          "x": 246,
          "y": 102
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-buckshot-briar": {
    "sprite": "x2-buckshot-briar",
    "parts": [
      {
        "width": 256,
        "height": 72
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 14.7,
        "derived": {
          "x": 253,
          "y": 14.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-buzzard-s-burnout": {
    "sprite": "x2-buzzard-s-burnout",
    "parts": [
      {
        "width": 256,
        "height": 190
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 48.2,
        "derived": {
          "x": 255,
          "y": 48.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-buzzard-s-eye-marksman": {
    "sprite": "x2-buzzard-s-eye-marksman",
    "parts": [
      {
        "width": 256,
        "height": 69
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 21.7,
        "derived": {
          "x": 255,
          "y": 21.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-calamity-howitzer": {
    "sprite": "x2-calamity-howitzer",
    "parts": [
      {
        "width": 256,
        "height": 88
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 16.8,
        "derived": {
          "x": 255,
          "y": 16.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-carom-coachgun": {
    "sprite": "x2-carom-coachgun",
    "parts": [
      {
        "width": 256,
        "height": 80
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17.8,
        "derived": {
          "x": 255,
          "y": 17.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-carom-king": {
    "sprite": "x2-carom-king",
    "parts": [
      {
        "width": 256,
        "height": 93
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17.9,
        "derived": {
          "x": 255,
          "y": 17.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-carrion-roost-necro-scepter": {
    "sprite": "x2-carrion-roost-necro-scepter",
    "parts": [
      {
        "width": 256,
        "height": 52
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 21.5,
        "derived": {
          "x": 255,
          "y": 21.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-caustic-drum-sweeper": {
    "sprite": "x2-caustic-drum-sweeper",
    "parts": [
      {
        "width": 256,
        "height": 150
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 73.1,
        "derived": {
          "x": 255,
          "y": 73.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-cinderbore-longrifle": {
    "sprite": "x2-cinderbore-longrifle",
    "parts": [
      {
        "width": 256,
        "height": 57
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 12.7,
        "derived": {
          "x": 255,
          "y": 12.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-cinderchoke-blunderbuss": {
    "sprite": "x2-cinderchoke-blunderbuss",
    "parts": [
      {
        "width": 256,
        "height": 121
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 47.5,
        "derived": {
          "x": 255,
          "y": 47.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-cinderfan-dragoon": {
    "sprite": "x2-cinderfan-dragoon",
    "parts": [
      {
        "width": 256,
        "height": 107
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 36.5,
        "derived": {
          "x": 255,
          "y": 36.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-cinderfang-derringer": {
    "sprite": "x2-cinderfang-derringer",
    "parts": [
      {
        "width": 256,
        "height": 144
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 23.3,
        "derived": {
          "x": 255,
          "y": 23.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-cinderquill-dart-caster": {
    "sprite": "x2-cinderquill-dart-caster",
    "parts": [
      {
        "width": 256,
        "height": 60
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 29.5,
        "derived": {
          "x": 255,
          "y": 29.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-coffin-nail-carbine": {
    "sprite": "x2-coffin-nail-carbine",
    "parts": [
      {
        "width": 256,
        "height": 89
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17.9,
        "derived": {
          "x": 255,
          "y": 17.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-coffinnail-driver": {
    "sprite": "x2-coffinnail-driver",
    "parts": [
      {
        "width": 256,
        "height": 85
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 6,
        "derived": {
          "x": 255,
          "y": 6
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-coyote-stinger": {
    "sprite": "x2-coyote-stinger",
    "parts": [
      {
        "width": 256,
        "height": 156
      },
      {
        "width": 256,
        "height": 156
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 35.2,
        "derived": {
          "x": 255,
          "y": 35.2
        }
      },
      {
        "part": 1,
        "x": 255,
        "y": 35.2,
        "derived": {
          "x": 255,
          "y": 35.2
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-doomsday-drum-cannon": {
    "sprite": "x2-doomsday-drum-cannon",
    "parts": [
      {
        "width": 256,
        "height": 130
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 60.1,
        "derived": {
          "x": 255,
          "y": 60.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-dustdevil-riotgun": {
    "sprite": "x2-dustdevil-riotgun",
    "parts": [
      {
        "width": 256,
        "height": 119
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 19.9,
        "derived": {
          "x": 255,
          "y": 19.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-dustline-lever-action": {
    "sprite": "x2-dustline-lever-action",
    "parts": [
      {
        "width": 256,
        "height": 49
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 7.7,
        "derived": {
          "x": 255,
          "y": 7.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-emberfan-pumpgun": {
    "sprite": "x2-emberfan-pumpgun",
    "parts": [
      {
        "width": 256,
        "height": 83
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 19.8,
        "derived": {
          "x": 255,
          "y": 19.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-embernail-repeater": {
    "sprite": "x2-embernail-repeater",
    "parts": [
      {
        "width": 256,
        "height": 156
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 251,
        "y": 50,
        "derived": {
          "x": 251,
          "y": 50
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-fool-s-gold-revolver": {
    "sprite": "x2-fool-s-gold-revolver",
    "parts": [
      {
        "width": 256,
        "height": 184
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 33.8,
        "derived": {
          "x": 255,
          "y": 33.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-frostbite-volley-gun": {
    "sprite": "x2-frostbite-volley-gun",
    "parts": [
      {
        "width": 256,
        "height": 165
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 33.5,
        "derived": {
          "x": 255,
          "y": 33.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-frostbore-scattergun": {
    "sprite": "x2-frostbore-scattergun",
    "parts": [
      {
        "width": 256,
        "height": 70
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.6,
        "derived": {
          "x": 255,
          "y": 13.6
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-frostfang-speargun": {
    "sprite": "x2-frostfang-speargun",
    "parts": [
      {
        "width": 256,
        "height": 63
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 21,
        "derived": {
          "x": 255,
          "y": 21
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-frostquill-compendium": {
    "sprite": "x2-frostquill-compendium",
    "parts": [
      {
        "width": 256,
        "height": 158
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 92.7,
        "derived": {
          "x": 253,
          "y": 92.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-galvanic-coachgun": {
    "sprite": "x2-galvanic-coachgun",
    "parts": [
      {
        "width": 256,
        "height": 99
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 20.9,
        "derived": {
          "x": 255,
          "y": 20.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-galvanic-overcasters": {
    "sprite": "x2-galvanic-overcasters",
    "parts": [
      {
        "width": 256,
        "height": 117
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 63.9,
        "derived": {
          "x": 255,
          "y": 63.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-ghostbolt-crossbow": {
    "sprite": "x2-ghostbolt-crossbow",
    "parts": [
      {
        "width": 256,
        "height": 136
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 252,
        "y": 63.5,
        "derived": {
          "x": 252,
          "y": 63.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-ghostwind-spectre-rail": {
    "sprite": "x2-ghostwind-spectre-rail",
    "parts": [
      {
        "width": 256,
        "height": 62
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.4,
        "derived": {
          "x": 255,
          "y": 13.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-glasswidow-hexweave": {
    "sprite": "x2-glasswidow-hexweave",
    "parts": [
      {
        "width": 256,
        "height": 121
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 61.5,
        "derived": {
          "x": 255,
          "y": 61.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-glasswidow-punchgun": {
    "sprite": "x2-glasswidow-punchgun",
    "parts": [
      {
        "width": 256,
        "height": 155
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 249,
        "y": 42.2,
        "derived": {
          "x": 249,
          "y": 42.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-grave-anchor-harpoon": {
    "sprite": "x2-grave-anchor-harpoon",
    "parts": [
      {
        "width": 256,
        "height": 125
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 62,
        "derived": {
          "x": 253,
          "y": 62
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-gravedog-auto-rifle": {
    "sprite": "x2-gravedog-auto-rifle",
    "parts": [
      {
        "width": 256,
        "height": 93
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 19.9,
        "derived": {
          "x": 255,
          "y": 19.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-gravelthroat-repeater": {
    "sprite": "x2-gravelthroat-repeater",
    "parts": [
      {
        "width": 256,
        "height": 143
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 67.9,
        "derived": {
          "x": 255,
          "y": 67.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-gravelung-punt-rifle": {
    "sprite": "x2-gravelung-punt-rifle",
    "parts": [
      {
        "width": 256,
        "height": 56
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.4,
        "derived": {
          "x": 255,
          "y": 13.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-graveshot-grenade-gun": {
    "sprite": "x2-graveshot-grenade-gun",
    "parts": [
      {
        "width": 256,
        "height": 103
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 34.8,
        "derived": {
          "x": 255,
          "y": 34.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-gravesinger-s-hex-wand": {
    "sprite": "x2-gravesinger-s-hex-wand",
    "parts": [
      {
        "width": 256,
        "height": 64
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 14,
        "derived": {
          "x": 255,
          "y": 14
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-gravewax-twin-idols": {
    "sprite": "x2-gravewax-twin-idols",
    "parts": [
      {
        "width": 256,
        "height": 151
      },
      {
        "width": 255,
        "height": 151
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 76.5,
        "derived": {
          "x": 255,
          "y": 76.5
        }
      },
      {
        "part": 1,
        "x": 254,
        "y": 74,
        "derived": {
          "x": 254,
          "y": 74
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-gravewind-rimfire": {
    "sprite": "x2-gravewind-rimfire",
    "parts": [
      {
        "width": 256,
        "height": 99
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 14.3,
        "derived": {
          "x": 255,
          "y": 14.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-grit-snubnose": {
    "sprite": "x2-grit-snubnose",
    "parts": [
      {
        "width": 256,
        "height": 165
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 26.1,
        "derived": {
          "x": 255,
          "y": 26.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hailshot-hand-maul": {
    "sprite": "x2-hailshot-hand-maul",
    "parts": [
      {
        "width": 256,
        "height": 108
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 16.2,
        "derived": {
          "x": 255,
          "y": 16.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hailspitter-pepperbox": {
    "sprite": "x2-hailspitter-pepperbox",
    "parts": [
      {
        "width": 256,
        "height": 164
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 44.3,
        "derived": {
          "x": 255,
          "y": 44.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hailstorm-coilgun": {
    "sprite": "x2-hailstorm-coilgun",
    "parts": [
      {
        "width": 256,
        "height": 70
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17.1,
        "derived": {
          "x": 255,
          "y": 17.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hallowbore-coachgun": {
    "sprite": "x2-hallowbore-coachgun",
    "parts": [
      {
        "width": 256,
        "height": 115
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 28,
        "derived": {
          "x": 255,
          "y": 20.1
        },
        "overrideReason": "The shared engraved muzzle plate joins both stacked barrels into one alpha mass; the two visible bore centres require explicit art-space points."
      },
      {
        "part": 0,
        "x": 255,
        "y": 51,
        "derived": {
          "x": 255,
          "y": 20.1
        },
        "overrideReason": "The shared engraved muzzle plate joins both stacked barrels into one alpha mass; the two visible bore centres require explicit art-space points."
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hellbore-gatling": {
    "sprite": "x2-hellbore-gatling",
    "parts": [
      {
        "width": 256,
        "height": 127
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 42,
        "derived": {
          "x": 255,
          "y": 42
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hellmouth-palmcaster": {
    "sprite": "x2-hellmouth-palmcaster",
    "parts": [
      {
        "width": 256,
        "height": 142
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 96.3,
        "derived": {
          "x": 255,
          "y": 96.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hexbolt-spitter-mitt": {
    "sprite": "x2-hexbolt-spitter-mitt",
    "parts": [
      {
        "width": 256,
        "height": 132
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 66.2,
        "derived": {
          "x": 255,
          "y": 66.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hexbore-voidmaw": {
    "sprite": "x2-hexbore-voidmaw",
    "parts": [
      {
        "width": 256,
        "height": 134
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 252,
        "y": 35.9,
        "derived": {
          "x": 252,
          "y": 35.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hexbore-witchrifle": {
    "sprite": "x2-hexbore-witchrifle",
    "parts": [
      {
        "width": 256,
        "height": 70
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 25.3,
        "derived": {
          "x": 255,
          "y": 25.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hollowpoint-hex": {
    "sprite": "x2-hollowpoint-hex",
    "parts": [
      {
        "width": 256,
        "height": 189
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 30.9,
        "derived": {
          "x": 255,
          "y": 30.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hollowpoint-repeater": {
    "sprite": "x2-hollowpoint-repeater",
    "parts": [
      {
        "width": 256,
        "height": 65
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 9.7,
        "derived": {
          "x": 255,
          "y": 9.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hollowpoint-voidgun": {
    "sprite": "x2-hollowpoint-voidgun",
    "parts": [
      {
        "width": 256,
        "height": 128
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 45.4,
        "derived": {
          "x": 255,
          "y": 45.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-hornet-s-nest-bolter": {
    "sprite": "x2-hornet-s-nest-bolter",
    "parts": [
      {
        "width": 256,
        "height": 154
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 252,
        "y": 71.7,
        "derived": {
          "x": 252,
          "y": 71.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-iron-marshal": {
    "sprite": "x2-iron-marshal",
    "parts": [
      {
        "width": 256,
        "height": 117
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17.6,
        "derived": {
          "x": 255,
          "y": 17.6
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-ironhail-pepperbox": {
    "sprite": "x2-ironhail-pepperbox",
    "parts": [
      {
        "width": 256,
        "height": 185
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 74.2,
        "derived": {
          "x": 255,
          "y": 74.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-ironhide-buffalo-gun": {
    "sprite": "x2-ironhide-buffalo-gun",
    "parts": [
      {
        "width": 256,
        "height": 84
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 34.9,
        "derived": {
          "x": 255,
          "y": 34.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-leviathan-harpoon-gun": {
    "sprite": "x2-leviathan-harpoon-gun",
    "parts": [
      {
        "width": 256,
        "height": 87
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 22.5,
        "derived": {
          "x": 253,
          "y": 22.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-magpie-scattergun": {
    "sprite": "x2-magpie-scattergun",
    "parts": [
      {
        "width": 256,
        "height": 256
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 18,
        "derived": {
          "x": 255,
          "y": 18
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-mauler-slug-thrower": {
    "sprite": "x2-mauler-slug-thrower",
    "parts": [
      {
        "width": 256,
        "height": 66
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 12.5,
        "derived": {
          "x": 255,
          "y": 12.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-mesa-hand-cannon": {
    "sprite": "x2-mesa-hand-cannon",
    "parts": [
      {
        "width": 256,
        "height": 134
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 28.4,
        "derived": {
          "x": 255,
          "y": 28.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-mesa-spine-thunder-stave": {
    "sprite": "x2-mesa-spine-thunder-stave",
    "parts": [
      {
        "width": 256,
        "height": 19
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 9.5,
        "derived": {
          "x": 255,
          "y": 9.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-mirage-coilrifle": {
    "sprite": "x2-mirage-coilrifle",
    "parts": [
      {
        "width": 256,
        "height": 49
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.5,
        "derived": {
          "x": 255,
          "y": 13.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-null-grimoire-of-the-hollow-page": {
    "sprite": "x2-null-grimoire-of-the-hollow-page",
    "parts": [
      {
        "width": 256,
        "height": 177
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 44,
        "derived": {
          "x": 254,
          "y": 44
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-nullsaint-reliquary": {
    "sprite": "x2-nullsaint-reliquary",
    "parts": [
      {
        "width": 256,
        "height": 116
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 104,
        "derived": {
          "x": 255,
          "y": 104
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-pale-horse-longgun": {
    "sprite": "x2-pale-horse-longgun",
    "parts": [
      {
        "width": 256,
        "height": 43
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 6.9,
        "derived": {
          "x": 255,
          "y": 6.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-pearl-of-penance-censer": {
    "sprite": "x2-pearl-of-penance-censer",
    "parts": [
      {
        "width": 256,
        "height": 74
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 35.5,
        "derived": {
          "x": 254,
          "y": 35.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-pearlbreech-volleygun": {
    "sprite": "x2-pearlbreech-volleygun",
    "parts": [
      {
        "width": 256,
        "height": 123
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 51.2,
        "derived": {
          "x": 255,
          "y": 51.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-permafrost-cryo-bracer": {
    "sprite": "x2-permafrost-cryo-bracer",
    "parts": [
      {
        "width": 256,
        "height": 84
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 42.5,
        "derived": {
          "x": 253,
          "y": 42.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-permafrost-siege-lobber": {
    "sprite": "x2-permafrost-siege-lobber",
    "parts": [
      {
        "width": 256,
        "height": 120
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 37.5,
        "derived": {
          "x": 255,
          "y": 37.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-pinwheel-caromer": {
    "sprite": "x2-pinwheel-caromer",
    "parts": [
      {
        "width": 256,
        "height": 143
      },
      {
        "width": 256,
        "height": 143
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 30.4,
        "derived": {
          "x": 255,
          "y": 30.4
        }
      },
      {
        "part": 1,
        "x": 255,
        "y": 30.3,
        "derived": {
          "x": 255,
          "y": 30.3
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-plaguespitter-flak-gun": {
    "sprite": "x2-plaguespitter-flak-gun",
    "parts": [
      {
        "width": 256,
        "height": 133
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 47,
        "derived": {
          "x": 255,
          "y": 47
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-powderkeg-mortar": {
    "sprite": "x2-powderkeg-mortar",
    "parts": [
      {
        "width": 256,
        "height": 126
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 39.4,
        "derived": {
          "x": 255,
          "y": 39.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-psalter-of-the-burning-halo": {
    "sprite": "x2-psalter-of-the-burning-halo",
    "parts": [
      {
        "width": 256,
        "height": 152
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 109.9,
        "derived": {
          "x": 255,
          "y": 109.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-quartzlight-wayfinder": {
    "sprite": "x2-quartzlight-wayfinder",
    "parts": [
      {
        "width": 256,
        "height": 146
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 72.5,
        "derived": {
          "x": 253,
          "y": 72.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-quicksilver-fanner": {
    "sprite": "x2-quicksilver-fanner",
    "parts": [
      {
        "width": 256,
        "height": 108
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 16,
        "derived": {
          "x": 255,
          "y": 16
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-quicksilver-slugthrower": {
    "sprite": "x2-quicksilver-slugthrower",
    "parts": [
      {
        "width": 256,
        "height": 53
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 11.7,
        "derived": {
          "x": 255,
          "y": 11.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-quicksilver-streetsweeper": {
    "sprite": "x2-quicksilver-streetsweeper",
    "parts": [
      {
        "width": 256,
        "height": 124
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 27.9,
        "derived": {
          "x": 255,
          "y": 27.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-quill-storm-repeater": {
    "sprite": "x2-quill-storm-repeater",
    "parts": [
      {
        "width": 256,
        "height": 185
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 241,
        "y": 108.9,
        "derived": {
          "x": 241,
          "y": 108.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-reliquary-nailcaster": {
    "sprite": "x2-reliquary-nailcaster",
    "parts": [
      {
        "width": 256,
        "height": 154
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 43,
        "derived": {
          "x": 250,
          "y": 46
        },
        "overrideReason": "The three exposed spike tips are intentionally isolated bayonet-like extrema, which the barrel-mass heuristic rejects."
      },
      {
        "part": 0,
        "x": 255,
        "y": 76,
        "derived": {
          "x": 250,
          "y": 46
        },
        "overrideReason": "The three exposed spike tips are intentionally isolated bayonet-like extrema, which the barrel-mass heuristic rejects."
      },
      {
        "part": 0,
        "x": 255,
        "y": 110,
        "derived": {
          "x": 250,
          "y": 46
        },
        "overrideReason": "The three exposed spike tips are intentionally isolated bayonet-like extrema, which the barrel-mass heuristic rejects."
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "cycle"
  },
  "x2-reliquary-repeater": {
    "sprite": "x2-reliquary-repeater",
    "parts": [
      {
        "width": 256,
        "height": 192
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 36.3,
        "derived": {
          "x": 255,
          "y": 36.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-ricochet-roulette": {
    "sprite": "x2-ricochet-roulette",
    "parts": [
      {
        "width": 256,
        "height": 123
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 30.1,
        "derived": {
          "x": 255,
          "y": 30.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-riftglass-prism-lantern": {
    "sprite": "x2-riftglass-prism-lantern",
    "parts": [
      {
        "width": 126,
        "height": 256
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 123,
        "y": 127,
        "derived": {
          "x": 123,
          "y": 127
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-rustwidow-pump-rifle": {
    "sprite": "x2-rustwidow-pump-rifle",
    "parts": [
      {
        "width": 256,
        "height": 63
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 7.7,
        "derived": {
          "x": 255,
          "y": 7.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-saintskull-monstrance": {
    "sprite": "x2-saintskull-monstrance",
    "parts": [
      {
        "width": 256,
        "height": 197
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 98.5,
        "derived": {
          "x": 254,
          "y": 98.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sanctum-brazier-staff": {
    "sprite": "x2-sanctum-brazier-staff",
    "parts": [
      {
        "width": 256,
        "height": 92
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 37.4,
        "derived": {
          "x": 254,
          "y": 37.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sanctus-siege-bombard": {
    "sprite": "x2-sanctus-siege-bombard",
    "parts": [
      {
        "width": 256,
        "height": 155
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 39.4,
        "derived": {
          "x": 255,
          "y": 39.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-scattershell-duster": {
    "sprite": "x2-scattershell-duster",
    "parts": [
      {
        "width": 253,
        "height": 128
      },
      {
        "width": 253,
        "height": 128
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 252,
        "y": 49,
        "derived": {
          "x": 251,
          "y": 37.2
        },
        "overrideReason": "Each akimbo sprite has two bores inside one opaque front plate; alpha exposes the plate edge but not the four bore centres."
      },
      {
        "part": 0,
        "x": 252,
        "y": 79,
        "derived": {
          "x": 251,
          "y": 37.2
        },
        "overrideReason": "Each akimbo sprite has two bores inside one opaque front plate; alpha exposes the plate edge but not the four bore centres."
      },
      {
        "part": 1,
        "x": 252,
        "y": 49,
        "derived": {
          "x": 251,
          "y": 37.2
        },
        "overrideReason": "Each akimbo sprite has two bores inside one opaque front plate; alpha exposes the plate edge but not the four bore centres."
      },
      {
        "part": 1,
        "x": 252,
        "y": 79,
        "derived": {
          "x": 251,
          "y": 37.2
        },
        "overrideReason": "Each akimbo sprite has two bores inside one opaque front plate; alpha exposes the plate edge but not the four bore centres."
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-scattershot-saint": {
    "sprite": "x2-scattershot-saint",
    "parts": [
      {
        "width": 256,
        "height": 127
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 30.4,
        "derived": {
          "x": 255,
          "y": 30.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-seraph-s-knuckle-reliquary": {
    "sprite": "x2-seraph-s-knuckle-reliquary",
    "parts": [
      {
        "width": 256,
        "height": 147
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 67.1,
        "derived": {
          "x": 255,
          "y": 67.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sidewinder-spitfire": {
    "sprite": "x2-sidewinder-spitfire",
    "parts": [
      {
        "width": 256,
        "height": 150
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 46.9,
        "derived": {
          "x": 253,
          "y": 46.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sidewinder-twin-rifles": {
    "sprite": "x2-sidewinder-twin-rifles",
    "parts": [
      {
        "width": 256,
        "height": 84
      },
      {
        "width": 256,
        "height": 84
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 13.8,
        "derived": {
          "x": 255,
          "y": 13.8
        }
      },
      {
        "part": 1,
        "x": 255,
        "y": 13.8,
        "derived": {
          "x": 255,
          "y": 13.8
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-slughammer-breachgun": {
    "sprite": "x2-slughammer-breachgun",
    "parts": [
      {
        "width": 256,
        "height": 112
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 27.4,
        "derived": {
          "x": 255,
          "y": 27.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-smoldering-eye-of-perdition": {
    "sprite": "x2-smoldering-eye-of-perdition",
    "parts": [
      {
        "width": 256,
        "height": 147
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 68.5,
        "derived": {
          "x": 254,
          "y": 68.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-snakebite-dart-slinger": {
    "sprite": "x2-snakebite-dart-slinger",
    "parts": [
      {
        "width": 256,
        "height": 96
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 26.5,
        "derived": {
          "x": 254,
          "y": 26.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-spitfire-censer-wand": {
    "sprite": "x2-spitfire-censer-wand",
    "parts": [
      {
        "width": 256,
        "height": 83
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 27.4,
        "derived": {
          "x": 255,
          "y": 27.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-spore-spitter-blunderbuss": {
    "sprite": "x2-spore-spitter-blunderbuss",
    "parts": [
      {
        "width": 256,
        "height": 129
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 66,
        "derived": {
          "x": 255,
          "y": 66
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-stormcaller-tesla-gatling": {
    "sprite": "x2-stormcaller-tesla-gatling",
    "parts": [
      {
        "width": 256,
        "height": 139
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 241,
        "y": 94,
        "derived": {
          "x": 255,
          "y": 99.9
        },
        "overrideReason": "Six recessed beam apertures sit inside one opaque front cap; alpha can derive the cap edge but cannot distinguish the six aperture centres."
      },
      {
        "part": 0,
        "x": 250,
        "y": 94,
        "derived": {
          "x": 255,
          "y": 99.9
        },
        "overrideReason": "Six recessed beam apertures sit inside one opaque front cap; alpha can derive the cap edge but cannot distinguish the six aperture centres."
      },
      {
        "part": 0,
        "x": 241,
        "y": 108,
        "derived": {
          "x": 255,
          "y": 99.9
        },
        "overrideReason": "Six recessed beam apertures sit inside one opaque front cap; alpha can derive the cap edge but cannot distinguish the six aperture centres."
      },
      {
        "part": 0,
        "x": 250,
        "y": 108,
        "derived": {
          "x": 255,
          "y": 99.9
        },
        "overrideReason": "Six recessed beam apertures sit inside one opaque front cap; alpha can derive the cap edge but cannot distinguish the six aperture centres."
      },
      {
        "part": 0,
        "x": 241,
        "y": 122,
        "derived": {
          "x": 255,
          "y": 99.9
        },
        "overrideReason": "Six recessed beam apertures sit inside one opaque front cap; alpha can derive the cap edge but cannot distinguish the six aperture centres."
      },
      {
        "part": 0,
        "x": 250,
        "y": 122,
        "derived": {
          "x": 255,
          "y": 99.9
        },
        "overrideReason": "Six recessed beam apertures sit inside one opaque front cap; alpha can derive the cap edge but cannot distinguish the six aperture centres."
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-stormspur-coil-carbine": {
    "sprite": "x2-stormspur-coil-carbine",
    "parts": [
      {
        "width": 256,
        "height": 63
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 15,
        "derived": {
          "x": 254,
          "y": 15
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sunbrand-hogleg": {
    "sprite": "x2-sunbrand-hogleg",
    "parts": [
      {
        "width": 256,
        "height": 92
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 12.9,
        "derived": {
          "x": 255,
          "y": 12.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sunbreaker-railgun": {
    "sprite": "x2-sunbreaker-railgun",
    "parts": [
      {
        "width": 256,
        "height": 47
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 10.6,
        "derived": {
          "x": 255,
          "y": 10.6
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-sunmote-reliquary-staff": {
    "sprite": "x2-sunmote-reliquary-staff",
    "parts": [
      {
        "width": 256,
        "height": 94
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 254,
        "y": 46.5,
        "derived": {
          "x": 254,
          "y": 46.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-tesla-drumbore": {
    "sprite": "x2-tesla-drumbore",
    "parts": [
      {
        "width": 256,
        "height": 166
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 66.6,
        "derived": {
          "x": 255,
          "y": 66.6
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-tesla-faradayer": {
    "sprite": "x2-tesla-faradayer",
    "parts": [
      {
        "width": 256,
        "height": 151
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 84.9,
        "derived": {
          "x": 255,
          "y": 84.9
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-thunderhead-lever-gun": {
    "sprite": "x2-thunderhead-lever-gun",
    "parts": [
      {
        "width": 256,
        "height": 87
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 17,
        "derived": {
          "x": 255,
          "y": 17
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-thunderhead-repeater-cannon": {
    "sprite": "x2-thunderhead-repeater-cannon",
    "parts": [
      {
        "width": 256,
        "height": 80
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 24.8,
        "derived": {
          "x": 255,
          "y": 24.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-thunderhead-spikecaster": {
    "sprite": "x2-thunderhead-spikecaster",
    "parts": [
      {
        "width": 256,
        "height": 59
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 21.5,
        "derived": {
          "x": 255,
          "y": 21.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-tidehook-bombarpoon": {
    "sprite": "x2-tidehook-bombarpoon",
    "parts": [
      {
        "width": 256,
        "height": 81
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 37.5,
        "derived": {
          "x": 253,
          "y": 37.5
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-tracer-saint-carbine": {
    "sprite": "x2-tracer-saint-carbine",
    "parts": [
      {
        "width": 256,
        "height": 57
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 11.7,
        "derived": {
          "x": 255,
          "y": 11.7
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-tumbleweed-skipper": {
    "sprite": "x2-tumbleweed-skipper",
    "parts": [
      {
        "width": 256,
        "height": 161
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 21.3,
        "derived": {
          "x": 255,
          "y": 21.3
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-twin-maw-greenerbore": {
    "sprite": "x2-twin-maw-greenerbore",
    "parts": [
      {
        "width": 256,
        "height": 106
      },
      {
        "width": 256,
        "height": 106
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 19.9,
        "derived": {
          "x": 255,
          "y": 19.9
        }
      },
      {
        "part": 1,
        "x": 255,
        "y": 19.9,
        "derived": {
          "x": 255,
          "y": 19.9
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-venomspine-repeater": {
    "sprite": "x2-venomspine-repeater",
    "parts": [
      {
        "width": 256,
        "height": 62
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 9.1,
        "derived": {
          "x": 255,
          "y": 9.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-voidgrasp-null-gauntlet": {
    "sprite": "x2-voidgrasp-null-gauntlet",
    "parts": [
      {
        "width": 256,
        "height": 111
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 55.8,
        "derived": {
          "x": 255,
          "y": 55.8
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-voidwell-idol": {
    "sprite": "x2-voidwell-idol",
    "parts": [
      {
        "width": 256,
        "height": 158
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 78.2,
        "derived": {
          "x": 255,
          "y": 78.2
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-voltcaster-machine-pistol": {
    "sprite": "x2-voltcaster-machine-pistol",
    "parts": [
      {
        "width": 256,
        "height": 192
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 39.1,
        "derived": {
          "x": 255,
          "y": 39.1
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-voltvein-conductors": {
    "sprite": "x2-voltvein-conductors",
    "parts": [
      {
        "width": 256,
        "height": 115
      },
      {
        "width": 255,
        "height": 114
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 57.4,
        "derived": {
          "x": 255,
          "y": 57.4
        }
      },
      {
        "part": 1,
        "x": 254,
        "y": 56.4,
        "derived": {
          "x": 254,
          "y": 56.4
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-whisperbarb-hand-crossbow": {
    "sprite": "x2-whisperbarb-hand-crossbow",
    "parts": [
      {
        "width": 256,
        "height": 91
      },
      {
        "width": 256,
        "height": 91
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 253,
        "y": 41.5,
        "derived": {
          "x": 253,
          "y": 41.5
        }
      },
      {
        "part": 1,
        "x": 253,
        "y": 41.5,
        "derived": {
          "x": 253,
          "y": 41.5
        }
      }
    ],
    "salvoMode": "cycle",
    "barrelMode": "parallel"
  },
  "x2-widowmaker-arbalest": {
    "sprite": "x2-widowmaker-arbalest",
    "parts": [
      {
        "width": 256,
        "height": 126
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 252,
        "y": 51,
        "derived": {
          "x": 252,
          "y": 51
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-widowmaker-cannon": {
    "sprite": "x2-widowmaker-cannon",
    "parts": [
      {
        "width": 256,
        "height": 151
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 40.4,
        "derived": {
          "x": 255,
          "y": 40.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  },
  "x2-wyrmgut-blunderbuss": {
    "sprite": "x2-wyrmgut-blunderbuss",
    "parts": [
      {
        "width": 256,
        "height": 119
      }
    ],
    "points": [
      {
        "part": 0,
        "x": 255,
        "y": 80.4,
        "derived": {
          "x": 255,
          "y": 80.4
        }
      }
    ],
    "salvoMode": "parallel",
    "barrelMode": "parallel"
  }
} as const satisfies Readonly<Record<string, WeaponArtMuzzleDefinition>>;
