// Generated by tools/artkit/gen-art-geometry.mjs from the committed orientation report.
// Do not hand-edit; reviewed unsafe-PCA overrides live in the generator.

export interface WeaponArtStateGeometry {
  readonly artAngle: number;
  readonly originX?: number;
  readonly originY?: number;
  readonly displayLengthMul?: number;
}

export interface WeaponArtGeometry {
  readonly closed: WeaponArtStateGeometry;
  readonly open?: WeaponArtStateGeometry;
}

export const REVIEWED_ART_AXIS_OUTLIER_IDS = [
  "x2-ashfall-peacemaker",
  "x2-emberleaf-chapbook",
  "x2-fool-s-gold-revolver",
  "x2-grit-snubnose",
  "x2-hexbloom-scattergrimoire",
  "x2-hollowpoint-hex",
  "x2-idol-of-the-pale-verdict",
  "x2-ironhail-pepperbox",
  "x2-riftglass-prism-lantern",
  "x2-tumbleweed-skipper"
] as const;

export const WEAPON_ART_GEOMETRY = {
  "x2-ashfall-peacemaker": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-codex-of-forked-tongues": {
    "closed": {
      "artAngle": 0,
      "originX": 0.12,
      "originY": 0.5,
      "displayLengthMul": 1
    },
    "open": {
      "artAngle": 0.033161256,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 1.195228609
    }
  },
  "x2-emberleaf-chapbook": {
    "closed": {
      "artAngle": 0,
      "originX": 0.15,
      "originY": 0.5,
      "displayLengthMul": 1
    },
    "open": {
      "artAngle": -0.048694686,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 1.333926321
    }
  },
  "x2-fool-s-gold-revolver": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-grit-snubnose": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-hexbloom-scattergrimoire": {
    "closed": {
      "artAngle": 0,
      "originX": 0.12,
      "originY": 0.5,
      "displayLengthMul": 1
    },
    "open": {
      "artAngle": -0.003490659,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 1.323372013
    }
  },
  "x2-hollowpoint-hex": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-idol-of-the-pale-verdict": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-ironhail-pepperbox": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-maledict-tome-of-salt-lines": {
    "closed": {
      "artAngle": 0,
      "originX": 0.1,
      "originY": 0.5,
      "displayLengthMul": 1
    },
    "open": {
      "artAngle": -0.000174533,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 1.168013904
    }
  },
  "x2-null-grimoire-of-the-hollow-page": {
    "closed": {
      "artAngle": 0,
      "originX": 0.13,
      "originY": 0.5,
      "displayLengthMul": 1
    },
    "open": {
      "artAngle": 0.045727626,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 1.122250348
    }
  },
  "x2-pyroglyph-spellbook": {
    "closed": {
      "artAngle": 0,
      "originX": 0.12,
      "originY": 0.5,
      "displayLengthMul": 1
    },
    "open": {
      "artAngle": -0.024958208,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 1.229054115
    }
  },
  "x2-riftglass-prism-lantern": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-tumbleweed-skipper": {
    "closed": {
      "artAngle": 0
    }
  },
  "x2-verdigris-grand-grimoire": {
    "closed": {
      "artAngle": 0,
      "originX": 0.09,
      "originY": 0.5,
      "displayLengthMul": 0.391666667
    },
    "open": {
      "artAngle": -0.05846853,
      "originX": 0.5,
      "originY": 0.85,
      "displayLengthMul": 0.328911074
    }
  },
} as const satisfies Readonly<Record<string, WeaponArtGeometry>>;

export function weaponArtGeometryFor(spriteId: string): WeaponArtGeometry | undefined {
  return (WEAPON_ART_GEOMETRY as Readonly<Record<string, WeaponArtGeometry>>)[spriteId];
}

