// AUTO-GENERATED by tools/artkit/gen-card-manifest.mjs — do not edit by hand.
// Weapon ids that have bespoke card art under public/cards/<id>.jpg. The §9 carousel
// preloads card art only for these (others use the sprite/icon fallback, §28.5).

export const CARD_ART_IDS = [
  "driftblade",
  "gravediggers-spade",
  "rattler-sabre",
  "rusty-cleaver",
  "tombstone-greatsword",
  "twin-bowie-fangs",
  "x-gun-coffin-shotgun",
  "x-gun-gatling",
  "x-gun-nailgun",
  "x-gun-revolver-cannon",
  "x-gun-ricochet-pistol",
  "x-sword-anchor",
  "x-sword-bone",
  "x-sword-buzzsaw",
  "x-sword-coffin",
  "x-sword-neon-katana",
  "x-sword-railspike",
] as const;
