// AUTO-GENERATED by tools/artkit/gen-card-manifest.mjs — do not edit by hand.
// Weapon ids that have bespoke card art under public/cards/<id>.png. The §9 carousel
// preloads card art only for these (others use the sprite/icon fallback, §28.5).

export const CARD_ART_IDS = [
  "driftblade",
  "rusty-cleaver",
  "tombstone-greatsword",
  "twin-bowie-fangs",
] as const;
