// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=decals-neon-cyber) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/decal-neon-cybers/, placed on the floor by ArenaScene.
export const DECAL_IDS_NEON_CYBER = [
  "decal-neon-cyber-00",
  "decal-neon-cyber-01",
  "decal-neon-cyber-02",
  "decal-neon-cyber-03",
  "decal-neon-cyber-04",
  "decal-neon-cyber-05",
  "decal-neon-cyber-06",
  "decal-neon-cyber-07",
  "decal-neon-cyber-08",
  "decal-neon-cyber-09",
] as const;
