// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=decals-ashlands) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/decal-ashlandss/, placed on the floor by ArenaScene.
export const DECAL_IDS_ASHLANDS = [
  "decal-ashlands-00",
  "decal-ashlands-01",
  "decal-ashlands-02",
  "decal-ashlands-03",
  "decal-ashlands-04",
  "decal-ashlands-05",
  "decal-ashlands-06",
  "decal-ashlands-07",
  "decal-ashlands-08",
  "decal-ashlands-09",
  "decal-ashlands-10",
] as const;
