// AUTO-GENERATED by tools/artkit/gen-decals.mjs — Codex decal prop-pack (§17 P4 ground dressing).
// Each id is a trimmed transparent PNG in public/decals/, scattered on the floor by ArenaScene.
export const DECAL_IDS = [
  "decal-00",
  "decal-01",
  "decal-02",
  "decal-03",
  "decal-04",
  "decal-05",
  "decal-06",
  "decal-07",
  "decal-08",
] as const;
