// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=decals-frostfell) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/decal-frostfells/, placed on the floor by ArenaScene.
export const DECAL_IDS_FROSTFELL = [
  "decal-frostfell-00",
  "decal-frostfell-01",
  "decal-frostfell-02",
  "decal-frostfell-03",
  "decal-frostfell-04",
  "decal-frostfell-05",
  "decal-frostfell-06",
  "decal-frostfell-07",
] as const;
