// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=decals-verdant-ruins) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/decal-verdant-ruinss/, placed on the floor by ArenaScene.
export const DECAL_IDS_VERDANT_RUINS = [
  "decal-verdant-ruins-00",
  "decal-verdant-ruins-01",
  "decal-verdant-ruins-02",
  "decal-verdant-ruins-03",
  "decal-verdant-ruins-04",
  "decal-verdant-ruins-05",
  "decal-verdant-ruins-06",
  "decal-verdant-ruins-07",
  "decal-verdant-ruins-08",
] as const;
