// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=icons-classes) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/icon-classess/, placed on the floor by ArenaScene.
export const ICONS_CLASSES = [
  "icon-classes-00",
  "icon-classes-01",
  "icon-classes-02",
  "icon-classes-03",
  "icon-classes-04",
  "icon-classes-05",
  "icon-classes-06",
  "icon-classes-07",
  "icon-classes-08",
] as const;
