// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=icons-stats) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/icon-statss/, placed on the floor by ArenaScene.
export const ICONS_STATS = [
  "icon-stats-00",
  "icon-stats-01",
  "icon-stats-02",
  "icon-stats-03",
  "icon-stats-04",
  "icon-stats-05",
  "icon-stats-06",
  "icon-stats-07",
  "icon-stats-08",
  "icon-stats-09",
] as const;
