// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=emotes) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/icon-emotess/, placed on the floor by ArenaScene.
export const ICONS_EMOTES = [
  "icon-emotes-00",
  "icon-emotes-01",
  "icon-emotes-02",
  "icon-emotes-03",
  "icon-emotes-04",
  "icon-emotes-05",
  "icon-emotes-06",
  "icon-emotes-07",
] as const;
