// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=icons-rarity) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/icon-raritys/, placed on the floor by ArenaScene.
export const ICONS_RARITY = [
  "icon-rarity-00",
  "icon-rarity-01",
  "icon-rarity-02",
  "icon-rarity-03",
  "icon-rarity-04",
  "icon-rarity-05",
  "icon-rarity-06",
  "icon-rarity-07",
] as const;
