// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=pois-neon-cyber) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/poi-neon-cybers/, placed on the floor by ArenaScene.
export const POI_IDS_NEON_CYBER = [
  "poi-neon-cyber-00",
  "poi-neon-cyber-01",
  "poi-neon-cyber-02",
  "poi-neon-cyber-03",
  "poi-neon-cyber-04",
  "poi-neon-cyber-05",
  "poi-neon-cyber-06",
] as const;
