// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=pois-verdant-ruins) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/poi-verdant-ruinss/, placed on the floor by ArenaScene.
export const POI_IDS_VERDANT_RUINS = [
  "poi-verdant-ruins-00",
  "poi-verdant-ruins-01",
  "poi-verdant-ruins-02",
  "poi-verdant-ruins-03",
  "poi-verdant-ruins-04",
  "poi-verdant-ruins-05",
] as const;
