// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=pois-ashlands) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/poi-ashlandss/, placed on the floor by ArenaScene.
export const POI_IDS_ASHLANDS = [
  "poi-ashlands-00",
  "poi-ashlands-01",
  "poi-ashlands-02",
  "poi-ashlands-03",
  "poi-ashlands-04",
  "poi-ashlands-05",
] as const;
