// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=pois-frostfell) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/poi-frostfells/, placed on the floor by ArenaScene.
export const POI_IDS_FROSTFELL = [
  "poi-frostfell-00",
  "poi-frostfell-01",
  "poi-frostfell-02",
  "poi-frostfell-03",
  "poi-frostfell-04",
  "poi-frostfell-05",
] as const;
