// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=pois) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/pois/, placed on the floor by ArenaScene.
export const POI_IDS = ["poi-00", "poi-01", "poi-02", "poi-03", "poi-04", "poi-05"] as const;
