// AUTO-GENERATED by tools/artkit/gen-w4r-projectiles.mjs. Do not edit by hand.
// Standalone in-flight identity sprites; generated entries use weapon art as reference, never as crop data.
export interface ProjectileSpriteManifestEntry {
  readonly url: string;
  readonly width: number;
  readonly height: number;
  readonly source: "generated" | "edited";
}
export const PROJECTILE_SPRITES = {
  "brimstone-rocket-warhead": {
    url: "projectiles/brimstone-rocket-warhead.png",
    width: 85,
    height: 80,
    source: "edited",
  },
  "ghostbolt-crossbow-arrow": {
    url: "projectiles/ghostbolt-crossbow-arrow.png",
    width: 240,
    height: 47,
    source: "generated",
  },
  "hand-mortar-shell": {
    url: "projectiles/hand-mortar-shell.png",
    width: 160,
    height: 73,
    source: "generated",
  },
  "hexbore-voidmaw-rune": {
    url: "projectiles/hexbore-voidmaw-rune.png",
    width: 144,
    height: 116,
    source: "generated",
  },
  "leviathan-harpoon-gun-harpoon": {
    url: "projectiles/leviathan-harpoon-gun-harpoon.png",
    width: 272,
    height: 66,
    source: "generated",
  },
  "mesa-hand-cannon-50cal": {
    url: "projectiles/mesa-hand-cannon-50cal.png",
    width: 160,
    height: 63,
    source: "generated",
  },
  "quill-storm-repeater-arrow": {
    url: "projectiles/quill-storm-repeater-arrow.png",
    width: 208,
    height: 63,
    source: "generated",
  },
  "saintskull-monstrance-holy-skull": {
    url: "projectiles/saintskull-monstrance-holy-skull.png",
    width: 162,
    height: 176,
    source: "generated",
  },
  "tidehook-bombarpoon-harpoon": {
    url: "projectiles/tidehook-bombarpoon-harpoon.png",
    width: 272,
    height: 92,
    source: "generated",
  },
  "widowmaker-arbalest-arrow": {
    url: "projectiles/widowmaker-arbalest-arrow.png",
    width: 272,
    height: 54,
    source: "generated",
  },
} as const satisfies Record<string, ProjectileSpriteManifestEntry>;

export type ProjectileSpriteId = keyof typeof PROJECTILE_SPRITES;
