// AUTO-GENERATED by tools/artkit/gen-w4r-projectiles.mjs. Do not edit by hand.
// Standalone in-flight identity sprites; generated entries use weapon art as reference, never as crop data.
export interface ProjectileSpriteManifestEntry {
  readonly url: string;
  readonly width: number;
  readonly height: number;
  readonly source: "generated" | "edited";
}
export const PROJECTILE_SPRITES = {
  "barrett-50cal-round": {
    url: "projectiles/barrett-50cal-round.png",
    width: 192,
    height: 45,
    source: "generated",
  },
  "brimstone-flaming-cross": {
    url: "projectiles/v7/brimstone-flaming-cross.png",
    width: 160,
    height: 86,
    source: "generated",
  },
  "brimstone-rocket-warhead": {
    url: "projectiles/brimstone-rocket-warhead.png",
    width: 85,
    height: 80,
    source: "edited",
  },
  "calamity-howitzer-battleship-shell": {
    url: "projectiles/calamity-howitzer-battleship-shell.png",
    width: 256,
    height: 87,
    source: "generated",
  },
  "coyotes-grin-throwing-blade": {
    url: "projectiles/coyotes-grin-throwing-blade.png",
    width: 192,
    height: 73,
    source: "generated",
  },
  "frostfang-pictured-harpoon": {
    url: "projectiles/v7/frostfang-pictured-harpoon.png",
    width: 272,
    height: 56,
    source: "generated",
  },
  "galvanic-coachgun-electric-slug": {
    url: "projectiles/v7/galvanic-coachgun-electric-slug.png",
    width: 128,
    height: 96,
    source: "generated",
  },
  "ghostbolt-crossbow-arrow": {
    url: "projectiles/ghostbolt-crossbow-arrow.png",
    width: 240,
    height: 47,
    source: "generated",
  },
  "hand-mortar-shell": {
    url: "projectiles/hand-mortar-shell.png",
    width: 160,
    height: 73,
    source: "generated",
  },
  "hexbore-voidmaw-rune": {
    url: "projectiles/hexbore-voidmaw-rune.png",
    width: 144,
    height: 116,
    source: "generated",
  },
  "ironhide-anti-tank-shell": {
    url: "projectiles/v7/ironhide-anti-tank-shell.png",
    width: 200,
    height: 48,
    source: "generated",
  },
  "leviathan-harpoon-gun-harpoon": {
    url: "projectiles/leviathan-harpoon-gun-harpoon.png",
    width: 272,
    height: 66,
    source: "generated",
  },
  "m50-50cal-round": {
    url: "projectiles/m50-50cal-round.png",
    width: 192,
    height: 47,
    source: "generated",
  },
  "mesa-hand-cannon-50cal": {
    url: "projectiles/mesa-hand-cannon-50cal.png",
    width: 160,
    height: 63,
    source: "generated",
  },
  "plaguespitter-green-shot": {
    url: "projectiles/v7/plaguespitter-green-shot.png",
    width: 120,
    height: 90,
    source: "generated",
  },
  "quill-storm-repeater-arrow": {
    url: "projectiles/quill-storm-repeater-arrow.png",
    width: 208,
    height: 63,
    source: "generated",
  },
  "ricochet-icicle": {
    url: "projectiles/v7/ricochet-icicle.png",
    width: 192,
    height: 63,
    source: "generated",
  },
  "saintskull-monstrance-holy-skull": {
    url: "projectiles/saintskull-monstrance-holy-skull.png",
    width: 162,
    height: 176,
    source: "generated",
  },
  "tesla-drumbore-electric-particle": {
    url: "projectiles/v7/tesla-drumbore-electric-particle.png",
    width: 106,
    height: 104,
    source: "generated",
  },
  "tesla-faradayer-hand-drawn-bolt": {
    url: "projectiles/v7/tesla-faradayer-hand-drawn-bolt.png",
    width: 192,
    height: 78,
    source: "generated",
  },
  "thunderhead-blue-helix": {
    url: "projectiles/v8/thunderhead-blue-helix.png",
    width: 176,
    height: 49,
    source: "generated",
  },
  "thunderhead-smoke-ring": {
    url: "projectiles/v8/thunderhead-smoke-ring.png",
    width: 128,
    height: 124,
    source: "generated",
  },
  "tidehook-bombarpoon-harpoon": {
    url: "projectiles/tidehook-bombarpoon-harpoon.png",
    width: 272,
    height: 92,
    source: "generated",
  },
  "widowmaker-arbalest-arrow": {
    url: "projectiles/widowmaker-arbalest-arrow.png",
    width: 272,
    height: 54,
    source: "generated",
  },
} as const satisfies Record<string, ProjectileSpriteManifestEntry>;

export type ProjectileSpriteId = keyof typeof PROJECTILE_SPRITES;
