// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-frost-nova) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-frost-novas/, placed on the floor by ArenaScene.
export const FX_FROST_NOVA = [
  "fx-frost-nova-00",
  "fx-frost-nova-01",
  "fx-frost-nova-02",
  "fx-frost-nova-03",
  "fx-frost-nova-04",
  "fx-frost-nova-05",
  "fx-frost-nova-06",
  "fx-frost-nova-07",
  "fx-frost-nova-08",
  "fx-frost-nova-09",
] as const;
