// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-grave-call) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-grave-calls/, placed on the floor by ArenaScene.
export const FX_GRAVE_CALL = [
  "fx-grave-call-00",
  "fx-grave-call-01",
  "fx-grave-call-02",
  "fx-grave-call-03",
  "fx-grave-call-04",
  "fx-grave-call-05",
  "fx-grave-call-06",
  "fx-grave-call-07",
  "fx-grave-call-08",
] as const;
