// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-quake-burst) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-quake-bursts/, placed on the floor by ArenaScene.
export const FX_QUAKE_BURST = [
  "fx-quake-burst-00",
  "fx-quake-burst-01",
  "fx-quake-burst-02",
  "fx-quake-burst-03",
  "fx-quake-burst-04",
  "fx-quake-burst-05",
  "fx-quake-burst-06",
  "fx-quake-burst-07",
] as const;
