// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-storm-call) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-storm-calls/, placed on the floor by ArenaScene.
export const FX_STORM_CALL = [
  "fx-storm-call-00",
  "fx-storm-call-01",
  "fx-storm-call-02",
  "fx-storm-call-03",
  "fx-storm-call-04",
  "fx-storm-call-05",
  "fx-storm-call-06",
  "fx-storm-call-07",
] as const;
