// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-lightning-ball) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-lightning-balls/, placed on the floor by ArenaScene.
export const FX_LIGHTNING_BALL = [
  "fx-lightning-ball-00",
  "fx-lightning-ball-01",
  "fx-lightning-ball-02",
  "fx-lightning-ball-03",
  "fx-lightning-ball-04",
  "fx-lightning-ball-05",
  "fx-lightning-ball-06",
  "fx-lightning-ball-07",
  "fx-lightning-ball-08",
  "fx-lightning-ball-09",
  "fx-lightning-ball-10",
] as const;
