// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-ember-eruption) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-ember-eruptions/, placed on the floor by ArenaScene.
export const FX_EMBER_ERUPTION = [
  "fx-ember-eruption-00",
  "fx-ember-eruption-01",
  "fx-ember-eruption-02",
  "fx-ember-eruption-03",
  "fx-ember-eruption-04",
  "fx-ember-eruption-05",
  "fx-ember-eruption-06",
  "fx-ember-eruption-07",
  "fx-ember-eruption-08",
  "fx-ember-eruption-09",
  "fx-ember-eruption-10",
] as const;
