// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-holy-smite) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-holy-smites/, placed on the floor by ArenaScene.
export const FX_HOLY_SMITE = [
  "fx-holy-smite-00",
  "fx-holy-smite-01",
  "fx-holy-smite-02",
  "fx-holy-smite-03",
  "fx-holy-smite-04",
  "fx-holy-smite-05",
  "fx-holy-smite-06",
  "fx-holy-smite-07",
  "fx-holy-smite-08",
  "fx-holy-smite-09",
] as const;
