// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-buzzsaw-wake) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-buzzsaw-wakes/, placed on the floor by ArenaScene.
export const FX_BUZZSAW_WAKE = [
  "fx-buzzsaw-wake-00",
  "fx-buzzsaw-wake-01",
  "fx-buzzsaw-wake-02",
  "fx-buzzsaw-wake-03",
  "fx-buzzsaw-wake-04",
  "fx-buzzsaw-wake-05",
  "fx-buzzsaw-wake-06",
  "fx-buzzsaw-wake-07",
  "fx-buzzsaw-wake-08",
] as const;
