// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-tide-crash) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-tide-crashs/, placed on the floor by ArenaScene.
export const FX_TIDE_CRASH = [
  "fx-tide-crash-00",
  "fx-tide-crash-01",
  "fx-tide-crash-02",
  "fx-tide-crash-03",
  "fx-tide-crash-04",
  "fx-tide-crash-05",
  "fx-tide-crash-06",
  "fx-tide-crash-07",
  "fx-tide-crash-08",
  "fx-tide-crash-09",
] as const;
