// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-nuke) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-nukes/, placed on the floor by ArenaScene.
export const FX_NUKE = [
  "fx-nuke-00",
  "fx-nuke-01",
  "fx-nuke-02",
  "fx-nuke-03",
  "fx-nuke-04",
  "fx-nuke-05",
  "fx-nuke-06",
  "fx-nuke-07",
  "fx-nuke-08",
  "fx-nuke-09",
  "fx-nuke-10",
] as const;
