// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-void-implosion) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-void-implosions/, placed on the floor by ArenaScene.
export const FX_VOID_IMPLOSION = [
  "fx-void-implosion-00",
  "fx-void-implosion-01",
  "fx-void-implosion-02",
  "fx-void-implosion-03",
  "fx-void-implosion-04",
  "fx-void-implosion-05",
  "fx-void-implosion-06",
  "fx-void-implosion-07",
  "fx-void-implosion-08",
  "fx-void-implosion-09",
] as const;
