// AUTO-GENERATED by tools/artkit/gen-decals.mjs (--pack=fx-toxic-burst) — Codex prop-pack (§17 P4).
// Each id is a trimmed transparent PNG in public/fx-toxic-bursts/, placed on the floor by ArenaScene.
export const FX_TOXIC_BURST = [
  "fx-toxic-burst-00",
  "fx-toxic-burst-01",
  "fx-toxic-burst-02",
  "fx-toxic-burst-03",
  "fx-toxic-burst-04",
  "fx-toxic-burst-05",
  "fx-toxic-burst-06",
  "fx-toxic-burst-07",
  "fx-toxic-burst-08",
  "fx-toxic-burst-09",
] as const;
