import type Phaser from "phaser";
import { PROJECTILE_SPRITES, type ProjectileSpriteId } from "../sprites/projectile-manifest.js";

export interface GunSpriteProjectileRecipe {
  readonly spriteId: string;
  readonly partRole: string;
  readonly crop: Readonly<{ x: number; y: number; width: number; height: number }>;
  readonly displayLength: number;
}

export interface GeneratedGunProjectileRecipe {
  readonly spriteId: ProjectileSpriteId;
  readonly url: string;
  readonly displayLength: number;
}

export type GeneratedThrownProjectileRecipe = GeneratedGunProjectileRecipe;

/** Legacy explicit own-sprite crop. New projectile identity work must use generated art below. */
export const GUN_SPRITE_PROJECTILES: Readonly<Partial<Record<string, GunSpriteProjectileRecipe>>> =
  Object.freeze({
    "x2-grave-anchor-harpoon": Object.freeze({
      spriteId: "x2-grave-anchor-harpoon",
      partRole: "part-1",
      crop: Object.freeze({ x: 183, y: 0, width: 73, height: 125 }),
      displayLength: 76,
    }),
  });

/** New reference-guided assets generated by the artkit Codex pipeline; never weapon crops. */
export const GUN_GENERATED_PROJECTILES: Readonly<
  Partial<Record<string, GeneratedGunProjectileRecipe>>
> = Object.freeze({
  "x2-barrett-50-cal-sniper": Object.freeze({
    spriteId: "barrett-50cal-round",
    url: PROJECTILE_SPRITES["barrett-50cal-round"].url,
    displayLength: 54,
  }),
  "x2-m50-anti-materiel-rifle": Object.freeze({
    spriteId: "m50-50cal-round",
    url: PROJECTILE_SPRITES["m50-50cal-round"].url,
    displayLength: 54,
  }),
  "x2-widowmaker-arbalest": Object.freeze({
    spriteId: "widowmaker-arbalest-arrow",
    url: PROJECTILE_SPRITES["widowmaker-arbalest-arrow"].url,
    displayLength: 78,
  }),
  "x2-tidehook-bombarpoon": Object.freeze({
    spriteId: "tidehook-bombarpoon-harpoon",
    url: PROJECTILE_SPRITES["tidehook-bombarpoon-harpoon"].url,
    displayLength: 92,
  }),
  "x2-saintskull-monstrance": Object.freeze({
    spriteId: "saintskull-monstrance-holy-skull",
    url: PROJECTILE_SPRITES["saintskull-monstrance-holy-skull"].url,
    displayLength: 96,
  }),
  "x2-quill-storm-repeater": Object.freeze({
    spriteId: "quill-storm-repeater-arrow",
    url: PROJECTILE_SPRITES["quill-storm-repeater-arrow"].url,
    displayLength: 44,
  }),
  "x2-mesa-hand-cannon": Object.freeze({
    spriteId: "mesa-hand-cannon-50cal",
    url: PROJECTILE_SPRITES["mesa-hand-cannon-50cal"].url,
    displayLength: 42,
  }),
  "x2-cinderbore-longrifle": Object.freeze({
    spriteId: "barrett-50cal-round",
    url: PROJECTILE_SPRITES["barrett-50cal-round"].url,
    displayLength: 46,
  }),
  "x-gun-hand-mortar": Object.freeze({
    spriteId: "hand-mortar-shell",
    url: PROJECTILE_SPRITES["hand-mortar-shell"].url,
    // The prior +400% order stays in gun.projectileVisualScale=5: 16px reference -> 80px live shell.
    displayLength: 16,
  }),
  "x2-ghostbolt-crossbow": Object.freeze({
    spriteId: "ghostbolt-crossbow-arrow",
    url: PROJECTILE_SPRITES["ghostbolt-crossbow-arrow"].url,
    displayLength: 72,
  }),
  "x2-leviathan-harpoon-gun": Object.freeze({
    spriteId: "leviathan-harpoon-gun-harpoon",
    url: PROJECTILE_SPRITES["leviathan-harpoon-gun-harpoon"].url,
    displayLength: 96,
  }),
  "x2-hexbore-voidmaw": Object.freeze({
    spriteId: "hexbore-voidmaw-rune",
    url: PROJECTILE_SPRITES["hexbore-voidmaw-rune"].url,
    displayLength: 48,
  }),
  "x2-brimstone-rocket-tube": Object.freeze({
    spriteId: "brimstone-rocket-warhead",
    url: PROJECTILE_SPRITES["brimstone-rocket-warhead"].url,
    displayLength: 50,
  }),
  "x2-brimstone-gallows-rifle": Object.freeze({
    spriteId: "brimstone-flaming-cross",
    url: PROJECTILE_SPRITES["brimstone-flaming-cross"].url,
    displayLength: 34,
  }),
  "x2-frostfang-speargun": Object.freeze({
    spriteId: "frostfang-pictured-harpoon",
    url: PROJECTILE_SPRITES["frostfang-pictured-harpoon"].url,
    displayLength: 96,
  }),
  "x2-hailbarrel-sledcaster": Object.freeze({
    spriteId: "hailbarrel-sledcaster-ice-puck",
    url: PROJECTILE_SPRITES["hailbarrel-sledcaster-ice-puck"].url,
    displayLength: 52,
  }),
  "x2-galvanic-coachgun": Object.freeze({
    spriteId: "galvanic-coachgun-electric-slug",
    url: PROJECTILE_SPRITES["galvanic-coachgun-electric-slug"].url,
    displayLength: 32,
  }),
  "x2-ironhide-buffalo-gun": Object.freeze({
    spriteId: "ironhide-anti-tank-shell",
    url: PROJECTILE_SPRITES["ironhide-anti-tank-shell"].url,
    displayLength: 72,
  }),
  "x2-quicksilver-streetsweeper": Object.freeze({
    spriteId: "streetsweeper-grenade-shell",
    url: PROJECTILE_SPRITES["streetsweeper-grenade-shell"].url,
    displayLength: 34,
  }),
  "x2-plaguespitter-flak-gun": Object.freeze({
    spriteId: "plaguespitter-green-shot",
    url: PROJECTILE_SPRITES["plaguespitter-green-shot"].url,
    displayLength: 34,
  }),
  "x2-tesla-drumbore": Object.freeze({
    spriteId: "tesla-drumbore-electric-particle",
    url: PROJECTILE_SPRITES["tesla-drumbore-electric-particle"].url,
    displayLength: 30,
  }),
  "x2-tesla-faradayer": Object.freeze({
    spriteId: "tesla-faradayer-hand-drawn-bolt",
    url: PROJECTILE_SPRITES["tesla-faradayer-hand-drawn-bolt"].url,
    displayLength: 68,
  }),
  "x2-thunderhead-lever-gun": Object.freeze({
    spriteId: "thunderhead-blue-helix",
    url: PROJECTILE_SPRITES["thunderhead-blue-helix"].url,
    displayLength: 68,
  }),
  "x2-thunderhead-repeater-cannon": Object.freeze({
    spriteId: "thunderhead-smoke-ring",
    url: PROJECTILE_SPRITES["thunderhead-smoke-ring"].url,
    displayLength: 62,
  }),
  "x2-calamity-howitzer": Object.freeze({
    spriteId: "calamity-howitzer-battleship-shell",
    url: PROJECTILE_SPRITES["calamity-howitzer-battleship-shell"].url,
    displayLength: 92,
  }),
  "x-gun-ricochet-pistol": Object.freeze({
    spriteId: "ricochet-icicle",
    url: PROJECTILE_SPRITES["ricochet-icicle"].url,
    displayLength: 44,
  }),
});

/** Generated standalone thrown identities. They supersede the held-sprite fallback without ever cropping
 * the held weapon, which is essential for Coyote's Grin's historically tiled source sheet. */
export const THROWN_GENERATED_PROJECTILES: Readonly<
  Partial<Record<string, GeneratedThrownProjectileRecipe>>
> = Object.freeze({
  "x2-coyote-s-grin": Object.freeze({
    spriteId: "coyotes-grin-throwing-blade",
    url: PROJECTILE_SPRITES["coyotes-grin-throwing-blade"].url,
    displayLength: 72,
  }),
});

export function preloadGeneratedGunProjectiles(scene: Phaser.Scene): void {
  for (const [weaponId, recipe] of Object.entries(GUN_GENERATED_PROJECTILES))
    if (recipe) scene.load.image(`gun-generated:${weaponId}`, recipe.url);
  for (const [weaponId, recipe] of Object.entries(THROWN_GENERATED_PROJECTILES))
    if (recipe) scene.load.image(`thrown-generated:${weaponId}`, recipe.url);
}

/** Non-crop projectile identities resolve to existing painted particle packs. */
export const GUN_PROJECTILE_ART_PACKS = Object.freeze({
  arrow: "steel-bolt",
  cannonball: "steel-orb",
  fireball: "fire-orb",
} as const);
