import type Phaser from "phaser";

export interface GunSpriteProjectileRecipe {
  readonly spriteId: string;
  readonly partRole: string;
  readonly crop: Readonly<{ x: number; y: number; width: number; height: number }>;
  readonly displayLength: number;
}

export interface GeneratedGunProjectileRecipe {
  readonly url: string;
  readonly displayLength: number;
}

/** Reference-image orders use bounded crops from the weapon's own installed sprite. */
export const GUN_SPRITE_PROJECTILES: Readonly<Partial<Record<string, GunSpriteProjectileRecipe>>> =
  Object.freeze({
    "x2-grave-anchor-harpoon": Object.freeze({
      spriteId: "x2-grave-anchor-harpoon",
      partRole: "part-1",
      crop: Object.freeze({ x: 183, y: 0, width: 73, height: 125 }),
      displayLength: 76,
    }),
    "x2-hexbore-voidmaw": Object.freeze({
      spriteId: "x2-hexbore-voidmaw",
      partRole: "part-1",
      crop: Object.freeze({ x: 139, y: 54, width: 28, height: 34 }),
      displayLength: 46,
    }),
    "x2-brimstone-rocket-tube": Object.freeze({
      spriteId: "x2-brimstone-rocket-tube",
      partRole: "part-1",
      crop: Object.freeze({ x: 158, y: 13, width: 98, height: 52 }),
      displayLength: 72,
    }),
  });

/** New reference-guided assets generated by the artkit Codex pipeline; never weapon crops. */
export const GUN_GENERATED_PROJECTILES: Readonly<
  Partial<Record<string, GeneratedGunProjectileRecipe>>
> = Object.freeze({
  "x2-widowmaker-arbalest": Object.freeze({
    url: "projectiles/widowmaker-arbalest-arrow.png",
    displayLength: 78,
  }),
  "x2-tidehook-bombarpoon": Object.freeze({
    url: "projectiles/tidehook-bombarpoon-harpoon.png",
    displayLength: 92,
  }),
});

export function preloadGeneratedGunProjectiles(scene: Phaser.Scene): void {
  for (const [weaponId, recipe] of Object.entries(GUN_GENERATED_PROJECTILES))
    if (recipe) scene.load.image(`gun-generated:${weaponId}`, recipe.url);
}

/** Non-crop projectile identities resolve to existing painted particle packs. */
export const GUN_PROJECTILE_ART_PACKS = Object.freeze({
  arrow: "steel-bolt",
  cannonball: "steel-orb",
  fireball: "fire-orb",
} as const);
