// AUTO-GENERATED by tools/artkit/gen-v6g-combat-sheets.mjs.
export interface KatanaSlashAssignment { readonly language: string; readonly color: string; readonly label: string; readonly key: string; readonly url: string; }
export const KATANA_SLASH_ASSIGNMENTS = Object.freeze({
  "x2-hailwidow-katana": Object.freeze({ language: "crescent", color: "#9eeaff", label: "splitting-hail crescent", key: "katana-slash:x2-hailwidow-katana", url: "particles/katana-slash-x2-hailwidow-katana.png" }),
  "x2-gravechill-nodachi": Object.freeze({ language: "seam", color: "#d9f7ff", label: "frozen fracture seam", key: "katana-slash:x2-gravechill-nodachi", url: "particles/katana-slash-x2-gravechill-nodachi.png" }),
  "x2-voltfang-tachi": Object.freeze({ language: "crosscut", color: "#ffe24a", label: "forked thunder cross-cut", key: "katana-slash:x2-voltfang-tachi", url: "particles/katana-slash-x2-voltfang-tachi.png" }),
  "x2-cinderfang-wakizashi-pair": Object.freeze({ language: "crosscut", color: "#ff6a2a", label: "ember twin cross-cut", key: "katana-slash:x2-cinderfang-wakizashi-pair", url: "particles/katana-slash-x2-cinderfang-wakizashi-pair.png" }),
  "x2-stormpetal-odachi": Object.freeze({ language: "inkstroke", color: "#ff9ecf", label: "petal-fiber ink stroke", key: "katana-slash:x2-stormpetal-odachi", url: "particles/katana-slash-x2-stormpetal-odachi.png" }),
  "drift-katana-stillwater-edict": Object.freeze({ language: "ripple", color: "#b9e7ff", label: "stillwater judicial ripple", key: "katana-slash:drift-katana-stillwater-edict", url: "particles/katana-slash-drift-katana-stillwater-edict.png" }),
  "drift-katana-stormthread": Object.freeze({ language: "crosscut", color: "#56a7ff", label: "blue storm-thread cross-cut", key: "katana-slash:drift-katana-stormthread", url: "particles/katana-slash-drift-katana-stormthread.png" }),
  "drift-katana-riftstep": Object.freeze({ language: "seam", color: "#b14bff", label: "violet rift-step seam", key: "katana-slash:drift-katana-riftstep", url: "particles/katana-slash-drift-katana-riftstep.png" }),
  "drift-nodachi-pale-horizon": Object.freeze({ language: "crescent", color: "#d8fbff", label: "pale horizon crescent", key: "katana-slash:drift-nodachi-pale-horizon", url: "particles/katana-slash-drift-nodachi-pale-horizon.png" }),
  "drift-nodachi-gatebreaker": Object.freeze({ language: "inkstroke", color: "#f1c06a", label: "gatebreaking dry brush", key: "katana-slash:drift-nodachi-gatebreaker", url: "particles/katana-slash-drift-nodachi-gatebreaker.png" }),
  "drift-greatkatana-moonwake": Object.freeze({ language: "crescent", color: "#e8e3ff", label: "lunar wake crescent", key: "katana-slash:drift-greatkatana-moonwake", url: "particles/katana-slash-drift-greatkatana-moonwake.png" }),
  "drift-greatkatana-tempest-regent": Object.freeze({ language: "ripple", color: "#d9b85f", label: "regent storm ripple", key: "katana-slash:drift-greatkatana-tempest-regent", url: "particles/katana-slash-drift-greatkatana-tempest-regent.png" }),
  "drift-colossal-world-seam": Object.freeze({ language: "seam", color: "#ff5eea", label: "colossal world seam", key: "katana-slash:drift-colossal-world-seam", url: "particles/katana-slash-drift-colossal-world-seam.png" }),
  "x-sword-neon-katana": Object.freeze({ language: "ripple", color: "#59fff2", label: "neon plasma ripple", key: "katana-slash:x-sword-neon-katana", url: "particles/katana-slash-x-sword-neon-katana.png" }),
}) satisfies Readonly<Record<string, KatanaSlashAssignment>>;
