// AUTO-GENERATED by tools/artkit/gen-particle-packs.mjs — §41 the Codex particle factory. Do not edit.
// Each pack is an equal-cell horizontal spritesheet of individually painted VFX particles (chroma-keyed +
// connected-component dissected from one cluster render). Consumed by vfx/particles.ts.
export interface ParticlePack {
  url: string;
  frameWidth: number;
  count: number;
}
export const PARTICLE_PACKS: Record<string, ParticlePack> = {
  "arcane-bolt": { url: "particles/arcane-bolt.png", frameWidth: 96, count: 10 },
  "arcane-mote": { url: "particles/arcane-mote.png", frameWidth: 96, count: 10 },
  "arcane-orb": { url: "particles/arcane-orb.png", frameWidth: 96, count: 10 },
  "arcane-ring": { url: "particles/arcane-ring.png", frameWidth: 96, count: 12 },
  "arcane-shard": { url: "particles/arcane-shard.png", frameWidth: 96, count: 10 },
  "arcane-wisp": { url: "particles/arcane-wisp.png", frameWidth: 96, count: 10 },
  "fire-bolt": { url: "particles/fire-bolt.png", frameWidth: 96, count: 12 },
  "fire-mote": { url: "particles/fire-mote.png", frameWidth: 96, count: 10 },
  "fire-orb": { url: "particles/fire-orb.png", frameWidth: 96, count: 12 },
  "fire-ring": { url: "particles/fire-ring.png", frameWidth: 96, count: 12 },
  "fire-shard": { url: "particles/fire-shard.png", frameWidth: 96, count: 12 },
  "fire-wisp": { url: "particles/fire-wisp.png", frameWidth: 96, count: 12 },
  "frost-bolt": { url: "particles/frost-bolt.png", frameWidth: 96, count: 10 },
  "frost-mote": { url: "particles/frost-mote.png", frameWidth: 96, count: 12 },
  "frost-orb": { url: "particles/frost-orb.png", frameWidth: 96, count: 11 },
  "frost-ring": { url: "particles/frost-ring.png", frameWidth: 96, count: 12 },
  "frost-shard": { url: "particles/frost-shard.png", frameWidth: 96, count: 10 },
  "frost-wisp": { url: "particles/frost-wisp.png", frameWidth: 96, count: 10 },
  "holy-bolt": { url: "particles/holy-bolt.png", frameWidth: 96, count: 10 },
  "holy-mote": { url: "particles/holy-mote.png", frameWidth: 96, count: 10 },
  "holy-orb": { url: "particles/holy-orb.png", frameWidth: 96, count: 10 },
  "holy-ring": { url: "particles/holy-ring.png", frameWidth: 96, count: 12 },
  "holy-shard": { url: "particles/holy-shard.png", frameWidth: 96, count: 10 },
  "holy-wisp": { url: "particles/holy-wisp.png", frameWidth: 96, count: 10 },
  "shock-bolt": { url: "particles/shock-bolt.png", frameWidth: 96, count: 10 },
  "shock-mote": { url: "particles/shock-mote.png", frameWidth: 96, count: 10 },
  "shock-orb": { url: "particles/shock-orb.png", frameWidth: 96, count: 10 },
  "shock-ring": { url: "particles/shock-ring.png", frameWidth: 96, count: 12 },
  "shock-shard": { url: "particles/shock-shard.png", frameWidth: 96, count: 12 },
  "shock-wisp": { url: "particles/shock-wisp.png", frameWidth: 96, count: 10 },
  "steel-bolt": { url: "particles/steel-bolt.png", frameWidth: 96, count: 10 },
  "steel-mote": { url: "particles/steel-mote.png", frameWidth: 96, count: 12 },
  "steel-orb": { url: "particles/steel-orb.png", frameWidth: 96, count: 12 },
  "steel-ring": { url: "particles/steel-ring.png", frameWidth: 96, count: 12 },
  "steel-shard": { url: "particles/steel-shard.png", frameWidth: 96, count: 11 },
  "steel-wisp": { url: "particles/steel-wisp.png", frameWidth: 96, count: 12 },
  "toxic-bolt": { url: "particles/toxic-bolt.png", frameWidth: 96, count: 10 },
  "toxic-mote": { url: "particles/toxic-mote.png", frameWidth: 96, count: 12 },
  "toxic-orb": { url: "particles/toxic-orb.png", frameWidth: 96, count: 12 },
  "toxic-ring": { url: "particles/toxic-ring.png", frameWidth: 96, count: 12 },
  "toxic-shard": { url: "particles/toxic-shard.png", frameWidth: 96, count: 10 },
  "toxic-wisp": { url: "particles/toxic-wisp.png", frameWidth: 96, count: 10 },
  "void-bolt": { url: "particles/void-bolt.png", frameWidth: 96, count: 9 },
  "void-mote": { url: "particles/void-mote.png", frameWidth: 96, count: 10 },
  "void-orb": { url: "particles/void-orb.png", frameWidth: 96, count: 10 },
  "void-ring": { url: "particles/void-ring.png", frameWidth: 96, count: 12 },
  "void-shard": { url: "particles/void-shard.png", frameWidth: 96, count: 10 },
  "void-wisp": { url: "particles/void-wisp.png", frameWidth: 96, count: 10 },
};
export const PARTICLE_PACK_IDS = Object.keys(PARTICLE_PACKS);
