// AUTO-GENERATED by tools/artkit/build-weapon-vfx.mjs — DO NOT EDIT.
// Bakes the Weaponsmith-authored VFX suites (assignments.json) for the live game (§14 CODE-8).
// Re-run `node tools/artkit/build-weapon-vfx.mjs` after authoring in the smith.

export interface WeaponVfxLayer {
  on: boolean;
  params: Record<string, number>;
}
export interface WeaponVfx {
  suite: Record<string, WeaponVfxLayer>;
  rot: number;
  /** Fixed authored VFX radius (px); falls back to VFX_RADIUS_DEFAULT (74) when absent. */
  vfxRadius?: number;
  /** Texture path under public/ for the painted hero skin (e.g. "vfx/rattler-sabre.png"). */
  hero?: string;
  scatter?: { url: string; frameWidth: number; frameHeight: number; count: number };
}

export const WEAPON_VFX: Record<string, WeaponVfx> = {
  "x-sword-buzzsaw": {
    suite: {
      "cleave-flash": {
        on: true,
        params: {
          intensity: 0.5,
        },
      },
      "saw-sparks": {
        on: true,
        params: {
          count: 26,
          color: 0.48,
        },
      },
      "hit-spark": {
        on: true,
        params: {
          count: 20,
          color: 0.05,
        },
      },
      "hero-skin": {
        on: true,
        params: {
          size: 1,
          rise: 0,
        },
      },
    },
    rot: 0,
    vfxRadius: 104,
    hero: "vfx/x-sword-buzzsaw.png",
  },
  driftblade: {
    suite: {
      "hero-skin": {
        on: true,
        params: {
          size: 1,
          rise: 0,
        },
      },
    },
    rot: 180,
    hero: "vfx/driftblade.png",
  },
  "rattler-sabre": {
    suite: {
      "hero-skin": {
        on: true,
        params: {
          size: 1,
          rise: 0,
        },
      },
    },
    rot: 0,
    hero: "vfx/rattler-sabre.png",
  },
  "x-sword-coffin": {
    suite: {
      "hero-skin": {
        on: true,
        params: {
          size: 1,
          rise: 0,
        },
      },
    },
    rot: 0,
    vfxRadius: 114,
    hero: "vfx/x-sword-coffin.png",
  },
  "x-sword-neon-katana": {
    suite: {
      "edge-trail": {
        on: true,
        params: {
          reach: 0.6,
          color: 0.46,
          len: 1.4,
        },
      },
      "blade-trail": {
        on: true,
        params: {
          reach: 1.1,
          color: 0.6,
          sweep: 1.7,
          thick: 0.22,
          lines: 6,
        },
      },
      "hit-spark": {
        on: true,
        params: {
          count: 19,
          color: 0.46,
        },
      },
      "arc-bolt": {
        on: true,
        params: {
          color: 0.45,
          jag: 0.465,
        },
      },
    },
    rot: 0,
    vfxRadius: 142,
  },
  "x-sword-bone": {
    suite: {
      // Cosmetic magma-scatter OFF (v0.57): the magma is now a REAL server projectile mechanic
      // (WeaponDef.scatter → exploding magma, §14 WYSIWYG), so the fake cosmetic fling is retired to
      // avoid double-rendering. (Hand-edited in the generated file because a re-bake is currently
      // unsafe — out/x-sword-bone/scatter art scratch is absent; AUDIT-4. Mirror in assignments.json.)
      "magma-scatter": {
        on: false,
        params: {
          count: 8,
          spread: 0.5,
          power: 1.4,
        },
      },
      "hit-spark": {
        on: true,
        params: {
          count: 10,
          color: 0.05,
        },
      },
      "impact-flash": {
        on: true,
        params: {
          intensity: 0.45,
        },
      },
    },
    rot: 0,
    vfxRadius: 104,
    scatter: {
      url: "vfx/x-sword-bone-scatter.png",
      frameWidth: 249,
      frameHeight: 249,
      count: 8,
    },
  },
  "x-sword-railspike": {
    suite: {},
    rot: 0,
    vfxRadius: 116,
  },
};
