// AUTO-GENERATED by tools/artkit/build-weapon-vfx.mjs — DO NOT EDIT.
// Bakes the Weaponsmith-authored VFX suites (assignments.json) ⊕ weapon-vfx-overrides.json (hand-edits
// that survive re-bakes — §14 AUDIT-4) for the live game (§14 CODE-8). To change output, edit those
// SOURCES then re-run `node tools/artkit/build-weapon-vfx.mjs` — never hand-edit this file.

export interface WeaponVfxLayer { on: boolean; params: Record<string, number>; }
export interface WeaponVfxPaintedAura {
  textureKey: string;
  url: string;
  /** Final width relative to the exact authoritative aura diameter. */
  diameterMultiplier: number;
  verticalScale: number;
  layers: number[];
  alpha: number;
  subjects: string[];
}
export interface WeaponVfxPaintedSwing {
  textureKey: string;
  url: string;
  /** Final forward width relative to the exact authoritative melee extent. */
  extentMultiplier: number;
  originX: number;
  tint: number;
  lifeMs: number;
  subjects: string[];
}
export interface WeaponVfxPaintedQuake {
  textureKey: string;
  url: string;
  /** Final width relative to the exact authoritative quake diameter. */
  diameterMultiplier: number;
  lifeMs: number;
  subjects: string[];
  removedSubjects: string[];
}
export type WeaponVfxGeneratedImageKind =
  | "fire-dragon-sweep"
  | "purple-crystal-burst"
  | "arcane-lance-projectile"
  | "fan-tornado";
export interface WeaponVfxGeneratedImageBase {
  textureKey: string;
  url: string;
  subject: string;
  signature: string;
  audioCue: string;
  lifeMs: number;
  poolSize: number;
  /** Optional held-blade affine registration; length 1 overlays the physical blade without extending reach. */
  bladeOverlay?: { lengthMultiplier: number; widthMultiplier: number };
}
export interface WeaponVfxGeneratedImageReplacement extends WeaponVfxGeneratedImageBase {
  kind: Exclude<WeaponVfxGeneratedImageKind, "fan-tornado">;
}
export interface WeaponVfxGeneratedImageFanTornado extends WeaponVfxGeneratedImageBase {
  kind: "fan-tornado";
  /** Installed spin phases. The sprite remains upright; only its texture frame advances. */
  frames: readonly [
    { readonly textureKey: string; readonly url: string },
    { readonly textureKey: string; readonly url: string },
    { readonly textureKey: string; readonly url: string },
  ];
  frameRate: number;
  /** Uniform growth above the shared damage envelope; never shrinks below it. */
  scalePulse: number;
}
export type WeaponVfxGeneratedImage =
  | WeaponVfxGeneratedImageReplacement
  | WeaponVfxGeneratedImageFanTornado;
export interface WeaponVfx {
  suite: Record<string, WeaponVfxLayer>;
  rot: number;
  /** Fixed authored VFX radius (px); falls back to VFX_RADIUS_DEFAULT (74) when absent. */
  vfxRadius?: number;
  /** Authored VFX spawn offset (game px) from the weapon anchor, applied rotated by aim (§14). */
  vfxOrigin?: { x: number; y: number };
  /** When true the VFX spawns at the in-game cursor (clamped, greatsword-quake style) (§14). */
  spawnAtCursor?: boolean;
  /** Texture path under public/ for the painted hero skin (e.g. "vfx/rattler-sabre.png"). */
  hero?: string;
  scatter?: { url: string; frameWidth: number; frameHeight: number; count: number };
  /** Suppress the synthesized suite when an explicit painted treatment owns the full silhouette. */
  suppressFallback?: boolean;
  paintedAura?: WeaponVfxPaintedAura;
  paintedSwing?: WeaponVfxPaintedSwing;
  paintedQuake?: WeaponVfxPaintedQuake;
  /** Generated-image subject that authoritatively replaces this weapon's procedural treatment. */
  generatedImage?: WeaponVfxGeneratedImage;
}

export const WEAPON_VFX: Record<string, WeaponVfx> = {
  "x-sword-buzzsaw": {
    "suite": {
      "cleave-flash": {
        "on": true,
        "params": {
          "intensity": 0.5
        }
      },
      "saw-sparks": {
        "on": true,
        "params": {
          "count": 26,
          "color": 0.48
        }
      },
      "hit-spark": {
        "on": true,
        "params": {
          "count": 20,
          "color": 0.05
        }
      }
    },
    "rot": 0,
    "vfxRadius": 134
  },
  "driftblade": {
    "suite": {},
    "rot": 180,
    "vfxRadius": 162
  },
  "x-sword-coffin": {
    "suite": {},
    "rot": 0,
    "vfxRadius": 114
  },
  "x-sword-neon-katana": {
    "suite": {
      "edge-trail": {
        "on": true,
        "params": {
          "reach": 0.6,
          "color": 0.46,
          "len": 1.4
        }
      },
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1.1,
          "paint": 0,
          "history": 1,
          "bodyAlpha": 0.72,
          "lipAlpha": 0.54,
          "color": 0.6,
          "sweep": 1.7,
          "thick": 0.22,
          "lines": 6
        }
      },
      "hit-spark": {
        "on": true,
        "params": {
          "count": 19,
          "color": 0.46
        }
      },
      "arc-bolt": {
        "on": true,
        "params": {
          "color": 0.45,
          "jag": 0.465
        }
      }
    },
    "rot": 0,
    "vfxRadius": 142
  },
  "x-sword-bone": {
    "suite": {
      "hit-spark": {
        "on": true,
        "params": {
          "count": 10,
          "color": 0.05
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.45
        }
      }
    },
    "rot": 0,
    "vfxRadius": 104,
    "scatter": {
      "url": "vfx/x-sword-bone-scatter.png",
      "frameWidth": 249,
      "frameHeight": 249,
      "count": 8
    }
  },
  "x-sword-railspike": {
    "suite": {},
    "rot": 0,
    "vfxRadius": 116
  },
  "drift-colossal-world-seam": {
    "suite": {
      "slash-arc": {
        "on": true,
        "params": {
          "reach": 1.4,
          "width": 10,
          "color": 0.5
        }
      },
      "edge-trail": {
        "on": true,
        "params": {
          "reach": 1.6,
          "color": 0.5,
          "len": 1.4
        }
      },
      "cleave-flash": {
        "on": true,
        "params": {
          "intensity": 1
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 6,
          "count": 10,
          "size": 1.05
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 1
        }
      }
    },
    "rot": 0,
    "vfxRadius": 240
  },
  "drift-greatkatana-moonwake": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 4,
          "history": 0.94,
          "bodyAlpha": 0.46,
          "lipAlpha": 0.68,
          "color": 0.55
        }
      },
      "drift-petals": {
        "on": true,
        "params": {
          "count": 14,
          "color": 0.55
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 2,
          "count": 8,
          "size": 0.9
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.82
        }
      }
    },
    "rot": 0,
    "vfxRadius": 190
  },
  "drift-greatkatana-tempest-regent": {
    "suite": {
      "edge-trail": {
        "on": true,
        "params": {
          "reach": 1.46,
          "color": 0.15,
          "len": 1.22
        }
      }
    },
    "rot": 0,
    "vfxRadius": 210
  },
  "drift-katana-riftstep": {
    "suite": {
      "twin-slash": {
        "on": true,
        "params": {
          "reach": 0.96,
          "paint": 6,
          "history": 0.72,
          "bodyAlpha": 0.3,
          "lipAlpha": 0.7,
          "color": 0.77
        }
      },
      "drift-petals": {
        "on": true,
        "params": {
          "count": 7,
          "color": 0.77
        }
      },
      "cleave-flash": {
        "on": true,
        "params": {
          "intensity": 0.66
        }
      }
    },
    "rot": 0,
    "vfxRadius": 112
  },
  "drift-katana-stillwater-edict": {
    "suite": {
      "slash-arc": {
        "on": true,
        "params": {
          "reach": 0.92,
          "width": 3,
          "color": 0.52
        }
      },
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 0.9,
          "paint": 2,
          "history": 0.58,
          "bodyAlpha": 0.34,
          "lipAlpha": 0.64,
          "color": 0.52
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.38
        }
      }
    },
    "rot": 0,
    "vfxRadius": 98
  },
  "drift-katana-stormthread": {
    "suite": {
      "edge-trail": {
        "on": true,
        "params": {
          "reach": 1.02,
          "color": 0.56,
          "len": 1.2
        }
      },
      "arc-bolt": {
        "on": true,
        "params": {
          "color": 0.56,
          "jag": 0.48
        }
      },
      "hit-spark": {
        "on": true,
        "params": {
          "count": 21,
          "color": 0.56
        }
      }
    },
    "rot": 0,
    "vfxRadius": 104
  },
  "drift-nodachi-gatebreaker": {
    "suite": {
      "slash-arc": {
        "on": true,
        "params": {
          "reach": 1.16,
          "width": 8,
          "color": 0.1
        }
      }
    },
    "rot": 0,
    "vfxRadius": 170
  },
  "drift-nodachi-pale-horizon": {
    "suite": {
      "edge-trail": {
        "on": true,
        "params": {
          "reach": 1.4,
          "color": 0.54,
          "len": 1.3
        }
      },
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 3,
          "history": 0.68,
          "bodyAlpha": 0.3,
          "lipAlpha": 0.62,
          "color": 0.54
        }
      },
      "drift-petals": {
        "on": true,
        "params": {
          "count": 9,
          "color": 0.54
        }
      }
    },
    "rot": 0,
    "vfxRadius": 150
  },
  "drift-wakizashi-hushglass": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 0.68,
          "paint": 5,
          "history": 0.82,
          "bodyAlpha": 0.22,
          "lipAlpha": 0.48,
          "color": 0.58
        }
      },
      "drift-petals": {
        "on": true,
        "params": {
          "count": 4,
          "color": 0.58
        }
      },
      "cleave-flash": {
        "on": true,
        "params": {
          "intensity": 0.28
        }
      }
    },
    "rot": 0,
    "vfxRadius": 72
  },
  "drift-wakizashi-kagewake": {
    "suite": {
      "twin-slash": {
        "on": true,
        "params": {
          "reach": 0.64,
          "paint": 1,
          "history": 0.48,
          "bodyAlpha": 0.44,
          "lipAlpha": 0.68,
          "color": 0.53
        }
      },
      "edge-trail": {
        "on": true,
        "params": {
          "reach": 0.7,
          "color": 0.53,
          "len": 0.55
        }
      },
      "hit-spark": {
        "on": true,
        "params": {
          "count": 9,
          "color": 0.53
        }
      }
    },
    "rot": 0,
    "vfxRadius": 68
  },
  "x2-brimstone-gallows-rifle": {
    "suite": {
      "muzzle-flash": {
        "on": true,
        "params": {
          "size": 1.34,
          "color": 0.03
        }
      },
      "tracer": {
        "on": true,
        "params": {
          "count": 2,
          "color": 0.03
        }
      },
      "shell-eject": {
        "on": true,
        "params": {
          "count": 2
        }
      }
    },
    "rot": 0,
    "vfxRadius": 86
  },
  "x2-cairnfall-monolith": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 0,
          "history": 0.92,
          "bodyAlpha": 0.2,
          "lipAlpha": 0.3,
          "color": 0.1
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 0,
          "count": 11,
          "size": 1
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.38
        }
      }
    },
    "rot": 0,
    "vfxRadius": 194
  },
  "x2-dawnwall-testament": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 4,
          "history": 0.88,
          "bodyAlpha": 0.18,
          "lipAlpha": 0.36,
          "color": 0.55
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 4,
          "count": 9,
          "size": 0.88
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.82
        }
      }
    },
    "rot": 0,
    "vfxRadius": 182
  },
  "x2-gravedog-auto-rifle": {
    "suite": {
      "muzzle-flash": {
        "on": true,
        "params": {
          "size": 0.84,
          "color": 0.09
        }
      },
      "tracer": {
        "on": true,
        "params": {
          "count": 3,
          "color": 0.09
        }
      },
      "shell-eject": {
        "on": true,
        "params": {
          "count": 1
        }
      }
    },
    "rot": 0,
    "vfxRadius": 72
  },
  "x2-nullwake-ordinance": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 6,
          "history": 0.94,
          "bodyAlpha": 0.16,
          "lipAlpha": 0.34,
          "color": 0.8
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 6,
          "count": 9,
          "size": 0.94
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.44
        }
      }
    },
    "rot": 0,
    "vfxRadius": 190
  },
  "x2-pyre-gallows-brand": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 1,
          "history": 0.9,
          "bodyAlpha": 0.2,
          "lipAlpha": 0.36,
          "color": 0.03
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 1,
          "count": 10,
          "size": 0.9
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.72
        }
      }
    },
    "rot": 0,
    "vfxRadius": 180
  },
  "x2-rimewrit-grave-slab": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 2,
          "history": 0.9,
          "bodyAlpha": 0.2,
          "lipAlpha": 0.34,
          "color": 0.54
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 2,
          "count": 9,
          "size": 0.86
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.5
        }
      }
    },
    "rot": 0,
    "vfxRadius": 186
  },
  "x2-stormrail-colossus": {
    "suite": {
      "blade-trail": {
        "on": true,
        "params": {
          "reach": 1,
          "paint": 3,
          "history": 0.88,
          "bodyAlpha": 0.18,
          "lipAlpha": 0.38,
          "color": 0.63
        }
      },
      "painted-impact": {
        "on": true,
        "params": {
          "paint": 3,
          "count": 10,
          "size": 0.84
        }
      },
      "impact-flash": {
        "on": true,
        "params": {
          "intensity": 0.78
        }
      }
    },
    "rot": 0,
    "vfxRadius": 176
  },
  "x2-stormspur-coil-carbine": {
    "suite": {
      "muzzle-flash": {
        "on": true,
        "params": {
          "size": 0.72,
          "color": 0.52
        }
      },
      "tracer": {
        "on": true,
        "params": {
          "count": 4,
          "color": 0.52
        }
      },
      "shell-eject": {
        "on": true,
        "params": {
          "count": 1
        }
      }
    },
    "rot": 0,
    "vfxRadius": 68
  },
  "x2-permafrost-bardiche": {
    "suite": {},
    "rot": 0,
    "vfxRadius": 250
  },
  "x2-quarry-splitter-bardiche": {
    "suite": {},
    "rot": 0,
    "vfxRadius": 296
  },
  "x2-mournveil-scythe": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true
  },
  "x2-fulgurite-storm-sphere": {
    "suite": {},
    "rot": 0,
    "paintedAura": {
      "textureKey": "b10:fulgurite-blue-fill",
      "url": "vfx/weapons/v7/fulgurite-blue-fill.png",
      "diameterMultiplier": 1,
      "verticalScale": 0.56,
      "layers": [
        1,
        0.62
      ],
      "alpha": 0.62,
      "subjects": [
        "blue-lightning",
        "storm-plates",
        "center-fill"
      ]
    }
  },
  "x2-dustreaper-zweihander": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true,
    "generatedImage": {
      "kind": "fire-dragon-sweep",
      "textureKey": "b11:fire-dragon",
      "url": "sprites/vfx-fire-dragon/part-1.png",
      "subject": "vfx-fire-dragon",
      "signature": "serpentine-fire-dragon-head-led-sweep",
      "audioCue": "b11:fire-dragon-sweep",
      "lifeMs": 520,
      "poolSize": 1,
      "bladeOverlay": {
        "lengthMultiplier": 1,
        "widthMultiplier": 1
      }
    }
  },
  "x2-mesa-heart-geodes": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true,
    "generatedImage": {
      "kind": "purple-crystal-burst",
      "textureKey": "b11:purple-crystal-family",
      "url": "sprites/vfx-purple-crystal-family/part-1.png",
      "subject": "vfx-purple-crystal-family",
      "signature": "dense-pooled-purple-geode-fragment-sweep",
      "audioCue": "b11:crystal-crack-hum",
      "lifeMs": 420,
      "poolSize": 6
    }
  },
  "x-staff-arcane-lance": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true,
    "generatedImage": {
      "kind": "arcane-lance-projectile",
      "textureKey": "b11:arcanist-lance",
      "url": "sprites/vfx-arcanist-lance/part-1.png",
      "subject": "vfx-arcanist-lance",
      "signature": "runic-arcane-blue-lance-projectile",
      "audioCue": "b11:arcane-lance-cast",
      "lifeMs": 220,
      "poolSize": 1
    }
  },
  "x2-iron-war-fan": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true,
    "generatedImage": {
      "kind": "fan-tornado",
      "textureKey": "b18:tornado:iron-gale",
      "url": "sprites/vfx-tornado-iron-gale/part-1.png",
      "subject": "vfx-tornado-iron-gale",
      "signature": "player-height-upright-iron-gale-projectile",
      "audioCue": "b18:iron-gale-whoosh",
      "lifeMs": 500,
      "poolSize": 1,
      "frames": [
        {
          "textureKey": "b18:tornado:iron-gale",
          "url": "sprites/vfx-tornado-iron-gale/part-1.png"
        },
        {
          "textureKey": "b37:tornado:iron-gale:2",
          "url": "sprites/vfx-tornado-iron-gale/part-2.png"
        },
        {
          "textureKey": "b37:tornado:iron-gale:3",
          "url": "sprites/vfx-tornado-iron-gale/part-3.png"
        }
      ],
      "frameRate": 10,
      "scalePulse": 0.06
    }
  },
  "x2-ember-fan": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true,
    "generatedImage": {
      "kind": "fan-tornado",
      "textureKey": "b18:tornado:ember-fire",
      "url": "sprites/vfx-tornado-ember-fire/part-1.png",
      "subject": "vfx-tornado-ember-fire",
      "signature": "player-height-upright-ember-fire-projectile",
      "audioCue": "b18:ember-fire-roar",
      "lifeMs": 500,
      "poolSize": 1,
      "frames": [
        {
          "textureKey": "b18:tornado:ember-fire",
          "url": "sprites/vfx-tornado-ember-fire/part-1.png"
        },
        {
          "textureKey": "b37:tornado:ember-fire:2",
          "url": "sprites/vfx-tornado-ember-fire/part-2.png"
        },
        {
          "textureKey": "b37:tornado:ember-fire:3",
          "url": "sprites/vfx-tornado-ember-fire/part-3.png"
        }
      ],
      "frameRate": 10,
      "scalePulse": 0.06
    }
  },
  "x2-storm-fan": {
    "suite": {},
    "rot": 0,
    "suppressFallback": true,
    "generatedImage": {
      "kind": "fan-tornado",
      "textureKey": "b18:tornado:storm-shock",
      "url": "sprites/vfx-tornado-storm-shock/part-1.png",
      "subject": "vfx-tornado-storm-shock",
      "signature": "player-height-upright-storm-shock-projectile",
      "audioCue": "b18:storm-thunder-crack",
      "lifeMs": 500,
      "poolSize": 1,
      "frames": [
        {
          "textureKey": "b18:tornado:storm-shock",
          "url": "sprites/vfx-tornado-storm-shock/part-1.png"
        },
        {
          "textureKey": "b37:tornado:storm-shock:2",
          "url": "sprites/vfx-tornado-storm-shock/part-2.png"
        },
        {
          "textureKey": "b37:tornado:storm-shock:3",
          "url": "sprites/vfx-tornado-storm-shock/part-3.png"
        }
      ],
      "frameRate": 10,
      "scalePulse": 0.06
    }
  },
  "x2-rimegut-ice-tongs": {
    "suite": {
      "hero-skin": {
        "on": true,
        "params": {
          "size": 1,
          "rise": 0
        }
      }
    },
    "rot": 0,
    "vfxRadius": 52,
    "hero": "vfx/x2-rimegut-ice-tongs.png",
    "suppressFallback": true
  }
};
